### ISSUE TITLE
Custom signals

### ISSUE THREAD

**Issue by pekim** [StefanSalewski/gintro#1]
I can't find anything in `gobject.nim` regarding registering or emitting custom signals (`g_signal_new`, `g_signal_emit`, ...).

For now I've used the [events](https://nim-lang.org/docs/events.html) module, to add an event listener to Widget subclasses. This works okay, but isn't perhaps as consistent as using gtk signals everywhere.

Is it planned to support custom signals? (Or have I overlooked support for them?) Should I plan on continuing to use nim events? Or is there a more idiomatic nim way of managing this for Widget subclasses?

**Comment by StefanSalewski** [comment]
That is a good question.  It may be the case that emitting custom signals is not directly supported by gobject-introspection at all, so we may have to create that code manually.

I am glade that events work for you already. I think I have never used emitting custom signals myself, can you provide a small C example or an example maybe in another language with C bindings?

**Comment by pekim** [comment]
I thought that I had used custom signals in `go`, but I haven't. I was getting confused with QT's slots and signals, which I've used.

Thinking about this more, my use case probably isn't really appropriate for custom signals. I'm now of the opinion that using an event emitter in a Widget subclass is perfectly reasonable and appropriate.

**Comment by StefanSalewski** [comment]
I will close this issue for now. For investigation of signal support I would need a working C example.

Please reopen when necessary.
