### ISSUE TITLE
How to use glade event handlers

### ISSUE THREAD

**Issue by adnan449** [StefanSalewski/gintro#105]
Glade makes it possible to connect to functions to emitted signals. In python they usually create a class called Handler and define methods there. And in Glade the author connects those methods names to appropriate signals: https://python-gtk-3-tutorial.readthedocs.io/en/latest/builder.html#example

Does Gintro offer any such solutions? Thank you.

**Comment by StefanSalewski** [comment]
From latest version of the GTK4 book, section http://ssalewski.de/gtkprogramming.html#_label:

> In the above code we connect our widgets to our callback functions by use of the connect macro. In principle that connection could be done in the XML UI files as well, but the gintro bindings do not support that currently and probably never will.

So connecting signals from within the XML UI files is currently not possible. Type safe connecting signals, for which variants of the mconnect macro are used, was one of the hardest part of the whole gintro bindings.

I have no idea how we may do it from the XML files, but I am not a Nim and macro expert. You may ask Araq or the other Nim core devs directly, maybe when you hire one of them for a few weeks they may find a solution. Maybe with some support of Mr. Bassi or Mr Droege from the Rust team, so it may be necessary to hire them also.

Unfortunately from a recent note of Mr. Bassi Glade does not really support GTK4, and currently no one is working to fix that.

**Comment by StefanSalewski** [comment]
What may work is creating a custom pragma that you then can attach to your callback functions in your source code. Would you really like that? We tried hard to avoid the cdecl pragma by generation trampoline functions for each callback, and now we create another pragma which we attach to the callbacks instead? Other solutions seems to be really hard-- just ask the Nim core devs about it.

**Comment by adnan449** [comment]
I personally do no think the lack of glade signal handlers is a big issue, I'd wait at least until Glade gets Gtk4 support.
