### ISSUE TITLE
gtk layer shell support

### ISSUE THREAD

**Issue by wilypomegranate** [StefanSalewski/gintro#110]
I was curious if https://github.com/wmww/gtk-layer-shell would be easy to support. I wanted to use nim for pinephone dev.

Some example bindings here: https://github.com/subgraph/gtk-layer-shell-rs

**Comment by StefanSalewski** [comment]
Dear Mr. Granate,

thank you for that hint. Unfortunately my Gentoo Linux provides only version 0.1 of that lib, which seems to be outdated. So I would have to install it from git sources to experiment with it. I am not sure if I could test the bindings on Linux at all, or if it would run on Phones only.

Generally we provide for all included packages at least a minimal example program. Would you be able to provide such an example?

**Comment by wilypomegranate** [comment]
So I have been able to test on my desktop as well. If I understand it correctly, the main requirement is wayland. I'm working on an app in it now; I will formulate it into an example.

Also thanks for all your work on this projects. It's great 👍

**Comment by StefanSalewski** [comment]
From the README:

>Layer shell is not supported on:
>Gnome-on-Wayland

I think so I will not be able to test it.

But I was able to install it from github sources. The gir files is really small, less than 700 lines. The gen.nim script generates a small

$ wc -l gtklayershell.nim 
232 gtklayershell.nim

module which compiles. I think as the modules is so small we can ship it without a test program.

I will try to push the new gintro version to github in the next days, I was struggling a bit with gstreamer issue, see

 https://discourse.gnome.org/t/glib-critical-for-use-of-gobject-intrspection/5402/16

But I think that is fixed now.

**Comment by StefanSalewski** [comment]
OK, GtkLayerShell has been added. You can test with

```
nimble install gintro@#head
```

You should note that the generated module files depend on the environment on which nimble install is executed, so the files differ for windows, mac and linux, and also for 32 or 64 bit systems. So I assume that you will have to run your "nimble install" command on your phone. Unfortunately I am not sure if someone has tested the gintro bindings on a 32 bit system at all. But maybe your Phone is 64 bit already.

**Comment by StefanSalewski** [comment]
```
$ ls -l ~/.nimble/pkgs/gintro-#v0.9.2/gintro/gtklayershell.nim 
-rw-r--r-- 1 salewski salewski 7922 Aug 13 14:16 /home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gtklayershell.nim
```

So it seems to be available. We have no example code yet. Closing.
