### ISSUE TITLE
Program doesn't run when I try to use a GTKBuilder file.

### ISSUE THREAD

**Issue by RainbowAsteroids** [StefanSalewski/gintro#111]
So I created a builder file ([login.ui](https://dpaste.com/9NVWS4NJJ)) and attempted to use it in the following Nim program:
```nim
import gintro/[gtk, glib, gobject, gio]

proc hello(b: Button, msg: string) = echo "Hello", msg

proc appActivate(app: Application) =
  let builder = newBuilder()
  discard builder.addFromFile("login.ui")
  let window = builder.getApplicationWindow("window")
  window.setApplication(app)

  var button = builder.getButton("loginButton")
  button.connect("clicked", hello, "")

let app = newApplication("xyz.portal2d.gtk")
connect(app, "activate", appActivate)
discard app.run
```
I end up getting a runtime error:
```
/mnt/1tb/Documents/Nim/gtk/src/main.nim(16) main
/home/rainbow/.nimble/pkgs/gintro-0.8.5/gintro/gio.nim(30246) run
/usr/lib/nim/core/macros.nim(559) connect_for_signal_cdecl_activate2
/mnt/1tb/Documents/Nim/gtk/src/main.nim(8) appActivate
/home/rainbow/.nimble/pkgs/gintro-0.8.5/gintro/gtk.nim(61741) getApplicationWindow
/usr/lib/nim/system/assertions.nim(30) failedAssertImpl
/usr/lib/nim/system/assertions.nim(23) raiseAssert
/usr/lib/nim/system/fatal.nim(49) sysFatal
Error: unhandled exception: /home/rainbow/.nimble/pkgs/gintro-0.8.5/gintro/gtk.nim(61741, 9) `toBool(g_type_check_instance_is_a(cast[ptr TypeInstance00](result.impl), gt))`  [AssertionDefect]
Error: execution of an external program failed: '/mnt/1tb/Documents/Nim/gtk/src/main '
```

**Comment by StefanSalewski** [comment]
The error message seems to be not that bad:

>gtk.nim(61741) getApplicationWindow

In your program you call getApplicationWindow() but in your ui file you declare it as plain GtkWindow.

In the gintro README we use ApplicationWindow for both. In the GTK4 book we have an example where we use GtkWindow for both. Seems to work too, as least for GTK4. For all of our examples with  XML UI files we used existing files. I never tried generation them with Glade myself.

One important note: Years ago we had issues from people reporting that they get empty windows with GtkBuilder. You may report the same soon. To fix that we added the visible property in the gintro README example:

  <object id="window" class="GtkApplicationWindow">
    <property name="visible">True</property>

But later some GTK core devs said that that is a bad idea, we should call showAll() on the main window in program code instead. So in the GTK4 book we did not set the visible property, see

http://ssalewski.de/gtkprogramming.html#_label

I think I should remove the visible property from the example in the README. But well then people will again complain about empty windows.

I hope there are no more errors in your XML UI file. XML UI with Glade is indeed a bit hard, I avoid it when possible. For details about the XML UI files, Glade and GtkBuilder you may ask in the Gnome forum, there are some people who know more about it.

**Comment by RainbowAsteroids** [comment]
> In your program you call getApplicationWindow() but in your ui file you declare it as plain GtkWindow.

Thanks for the catch.
> XML UI with Glade is indeed a bit hard, I avoid it when possible.

I come from Python and I used Qt Designer and PySide2 to generate my UIs, so idk if Qt Designer is any more easier than Glade.
