### ISSUE TITLE
Align enum generated with 'end'

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#117]
```nim
type
  Align* {.size: sizeof(cint), pure.} = enum
    fill = 0
    start = 1
    `end` = 2
    center = 3
    baseline = 4
```

Is there any reason that end is a string?   

------------------------------------------------------
This is of course not a problem, just funny, the end is highlighted in a different color.
![image](https://user-images.githubusercontent.com/30507409/111438279-1ddcba80-8715-11eb-865f-61ae6f280639.png)  
PS Also idk why but autosuggest cant complete values of any enams, so every time I open it via goto to see the possible values in the generated bindings.(

**Comment by SolitudeSF** [comment]
end is a nim keyword, so it has to be stropped, thats why its highlighted differently.
