### ISSUE TITLE
Frame with "nil" as parameter

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#12]
If, instead of a "cstring", the value "nil" is provided in "gtk_frame_new", the frame is drawn without label. But the wrapper "newFrame" crashes if the value "nil" is provided. This is due to the conversion from "string" to "cstring".

Passing an empty "string" is not a solution as the room for the label is still reserved and the result looks different.

I have built an overloaded "newFrame" without the label parameter and it works fine. Another way would be to add at the beginning a line such as "let label = if isNil(label): nil else: cstring(label)", but I think this is less clean.

This situation may exist for other widgets, but I have already seen some overloaded procedures for that.

**Comment by StefanSalewski** [comment]
Thanks for reporting. Have just tested and asked Araq.

```nim
var
  s: string = nil
  cs: cstring

cs = cstring(s)
echo cs.isNil # false
echo cs # crash
```

Old issue:

https://github.com/nim-lang/Nim/issues/1577

Araq told me that default of nil for uninitialized strings will vanish soon. I am not sure what that means for GTK, as we need nil values...

I will see if I can remove the crash, maybe just removing the conversion to cstring, it is not necessary.

**Comment by lscrd** [comment]
Just encountered a similar problem with "newScrolledWindow" which takes two adjustments as arguments. Generally, we don’t care to create the adjustments and we use the default ones by passing "nil" for both.

The same thing exists also for "newLabel", but passing an empty string works fine in this case.

**Comment by StefanSalewski** [comment]
Have fixed the problem for strings. For other data types that allow nil it is harder, maybe only manual fixes will work properly.

For the strings: Now nil is default when may_be_null() is reported from gobject introspection, and cstring() is replaced by safeStringToCString(). May change when Nim does not allow nil for strings later.

```nim
import gintro/[gtk, glib, gobject]
import gintro/gio except Application, newApplication

proc buttonClicked (button: Button) =
  button.label = utf8Strreverse(button.label, -1)

proc activate (app: Application) =
  let window = newApplicationWindow(app)
  window.borderWidth = 10
  window.title = "GNOME Button"
  window.defaultSize = (250, 50)
  let button = newButton("Click Me")
  button.borderWidth = 10
  let str: string = nil #"frame"
  #let frame = newFrame("frame") # was working already
  # let frame = newFrame(nil) # works also
  let frame = newFrame() # too
  # let frame = newFrame(str) # too
  frame.add(button)
  window.add(frame)
  button.connect("clicked",  buttonClicked)
  window.showAll

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", activate)
  discard app.run

main()
```

**Comment by StefanSalewski** [comment]
I tried to fix problem for objects too: Minimal changes for gen.nim only:

```
$ diff gintro/tests/gen.nim gitest/tests/gen.nim
2c2
< # v 0.2 2017-SEP-17
---
> # v 0.2 2017-SEP-18
393c393,398
<       arglist.add("cast[" & genRec(t, false) & "](" & name & ".impl)")
---
>       ##############
>       if mayBeNil:
>         #arglist.add("if $1.isNil: nil else: cast[" & genRec(t, false) & "]($1.impl)" % name)
>         arglist.add("if " & name & ".isNil: nil else: cast[" & genRec(t, false) & "](" & name & ".impl)")
>       else:
>         arglist.add("cast[" & genRec(t, false) & "](" & name & ".impl)")
421a427,430
> 
>     if genProxy and isProxyCandidate(t) and mayBeNil:
>       str.add(" = nil")

```

But big impact on glue code of course...

Seems to be OK:

```nim
# nim c label.nim
import gintro/[gtk, gio, glib, gobject]

proc activate(app: Application) =
  let window = newApplicationWindow(app)
  let label = newLabel("Yellow text on green background")
  var a1, a2: Adjustment
  #let scrolled = newScrolledWindow(a1, a2) #works
  #let scrolled = newScrolledWindow(a1) # works
  let scrolled = newScrolledWindow() # works
  #let scrolled = newScrolledWindow(nil) # works
  #let scrolled = newScrolledWindow(nil, nil) #works
  let aa1 = newAdjustment(0, 0, 100, 10, 10, 10)
  let aa2 = newAdjustment(0, 0, 100, 10, 10, 10)
  #let scrolled = newScrolledWindow(aa1, aa2) # seems to work also
  #let scrolled = newScrolledWindow(aa1) # OK
  #let scrolled = newScrolledWindow(nil, aa1) # OK
  #let scrolled = newScrolledWindow(aa1, nil) # OK
  let cssProvider = newCssProvider()
  let data = "label {color: yellow; background: green;}"
  #discard cssProvider.loadFromPath("doesnotexist")
  discard cssProvider.loadFromData(data)
  let styleContext = label.getStyleContext
  assert styleContext != nil
  addProvider(styleContext, cssProvider, STYLE_PROVIDER_PRIORITY_USER)
  scrolled.add(label)
  window.add(scrolled)
  showAll(window)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", activate)
  discard run(app)

main()
```
Closing, please reopen if necesary.
