### ISSUE TITLE
width-request property of widget is missing 

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#121]
https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget--width-request  
Found only setSizeRequest for both width and height

**Comment by StefanSalewski** [comment]
Yes. When you have some basic knowledge about GTK then you know that for setting or querying some important properties functions are available, but not for all properties.

For the later we have to set them directly. I can not remember details, but I can remember that at least in the GTK4 book I gave an example, to set dark theme. Searching in the book for term "dark" points us to

http://ssalewski.de/gtkprogramming.html#_label

I can not remember if I wrote something in the gintro README about setting or getting properties. But I guess GTK4 example should work for GTK3 too. And it is not very different as to Python or other bindings. Maybe ask on GTK forum for more details.
