### ISSUE TITLE
Why SourceView named View in bingings 

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#123]
I already thought that it was not there until I started searching in bindings, going through each subsequent mention of `type`, recognizing it by inheritance from TextView

**Comment by StefanSalewski** [comment]
```
grep -A8 "class name=\"View\"" /opt/gtk/share/gir-1.0/GtkSource-5.gir 
    <class name="View"
           c:symbol-prefix="view"
           c:type="GtkSourceView"
           parent="Gtk.TextView"
           glib:type-name="GtkSourceView"
           glib:get-type="gtk_source_view_get_type"
           glib:type-struct="ViewClass">
      <source-position filename="../gtksourceview/gtksourceview.h" line="105"/>
      <implements name="Gtk.Accessible"/>
```

So the GIR file name is GtkSource-5.gir ommitting view, and the class name is View.

You may ask the gtk core devs why they named it this way.

For the GTK4 book an GtkSourceView example was planned, I have it already on my local box, related to my old NED text editor. But GtkSourceView needs a lot of explanations, it is not an easy lib. And I think I mentioned GtkSourceView in the README where I may gave a textview example.
