### ISSUE TITLE
How to set constructor only parameters

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#124]
For example I wanna set priority like here https://gitlab.gnome.org/GNOME/gtksourceview/-/blob/master/tests/test-completion.c#L486  
  
But its `constructor set` parameter as I see [here](https://valadoc.org/gtksourceview-5/Gtk.SourceCompletionSnippets.html)  
So in Vala it will looks like this:  
![image](https://user-images.githubusercontent.com/30507409/115166171-54ae4380-a0ba-11eb-910a-576c92c54352.png)

**Comment by StefanSalewski** [comment]
Are you writing a GTK4 Nim editor? I started porting my NEd editor to GTK4 with gintro early this year, but GtkSourceView is a bit difficult unfortunately, so I may continue not before next winter.
For your question: I see no real problems:

```
snippet_provider = gtk_source_completion_snippets_new ();
g_object_set (snippet_provider, "priority", 20, NULL);
gtk_source_completion_add_provider (completion, GTK_SOURCE_COMPLETION_PROVIDER (snippet_provider)); 
```

```
grep -A4 "gtk_source_completion_snippets_new(" ~/.nimble/pkgs/gintro-#head/gintro/gtksource5.nim 
proc gtk_source_completion_snippets_new(): ptr CompletionSnippets00 {.
    importc, libprag.}

proc newCompletionSnippets*(): CompletionSnippets =
```

```
grep -A4 "gtk_source_completion_add_provider(" ~/.nimble/pkgs/gintro-#head/gintro/gtksource5.nim 
proc gtk_source_completion_add_provider(self: ptr Completion00; provider: ptr CompletionProvider00) {.
    importc, libprag.}

proc addProvider*(self: Completion; provider: CompletionProvider | CompletionWords | CompletionSnippets) =
```

So newCompletionSnippets*() and addProvider*() is available. And how you set properties is explained in the README as well as in the GTK4 book. In the README:

#window.header.setProperty("margin_start", toIntVal(10))

Well setting properties this way is maybe not that nice, and we need the toXXXVal function for each data type. But it should work.

**Comment by gavr123456789** [comment]
Not exactly. I want to experiment and create something similar to the Class Browser from Pharo.  
![image](https://user-images.githubusercontent.com/30507409/115192502-93142480-a0f3-11eb-9585-9a4749a51a82.png)
  
I was thinking about setProperty, but all the properties I've come across before had getter=, so it seemed to me that this might be a bug related to the constructor modifier.  
  
But perhaps gtksourceview 5 still has problems. https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/181#note_1085456   
And also no hith level lang examples https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/183.  
I dont know any project that using gtksourceview 5 already.

**Comment by StefanSalewski** [comment]
In

https://github.com/StefanSalewski/gintro/issues/121

I told you already that only important, often used properties has getter and setter procs by default.

For gtksourceview, there is the related tepl library. I think that one shall make writing editors more easy, but I have still to learn that. It is a bit sad that gedit, a simple editor, needs more than 100k lines of code. Gtksourceview support is generally not great, there is one person which is interested on working on it, he made a unsuccessful attempt to collect some money for his work, and there is the gnome builder guy, who uses gtksourceview. Both are not really active in gnome forum. Well there is also the geany editor, I think written in Vala. I never looked at that one.

**Comment by gavr123456789** [comment]
> It is a bit sad that gedit, a simple editor, needs more than 100k lines of code  
I think it's not as simple as it looks, there's a plugin system, and yet it's written in C. By the way, it is being rewritten from scratch, as far as I understand because of the not very good architecture.  
https://gitlab.gnome.org/GNOME/gnome-text-editor  
https://blogs.gnome.org/chergert/2021/03/06/a-gtk-4-based-text-editor/  
  
Here some Vala projects IDE:  
* [elementary code](https://github.com/elementary/code)  
* old dead [Valama](https://github.com/Valama/valama)  
* [roobuilder](https://github.com/roojs/app.Builder.js) strange mix of js and vala ide https://www.roojs.com/blog.php/View.html?page=5  
* [Proton](https://github.com/raggesilver/proton) Atom like IDE but GTK. I think it is the best one for getting examples.   
  
   
 Ou, I didnt know about [templ](https://gitlab.gnome.org/Archive/tepl/-/tree/master), again no higth level lang examples arr.
