### ISSUE TITLE
There are no information that gtk4.StringList implements gio.ListModel interface

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#127]
I'm trying to rewrite this [ListView example](https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec24.md)   
```nim
import gintro/[gtk4, gobject, gio]
import std/with

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(newLabel(""))
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  var 
    lb = listitem.getChild().Label
    # strobj = listitem.getItem().StringObject
    # txt = gtk4.getString(strobj)
  lb.text = "txt"

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild (nil)

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
  
  var 
    sl = gtk4.newStringList("one", "two", "three", "four")
    ls = cast[ListModel](sl)
    ns = gtk4.newNoSelection(ls)
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
  
  scr.setChild lv


  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)


  with window:
    title = "Nim ListView"
    setChild scr
    show
  


proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()

```  
  
So I need to use unsafe C cast like `cast[ListModel](sl)` to put StringList into NoSelection.   
But StringList already implements ListModel interfase.  
  
![image](https://user-images.githubusercontent.com/30507409/119261608-d117d300-bbe0-11eb-8a3c-03d0f789b828.png)  
  
Since Nim has no concept of an interface, and the concepts are currently being reworked, I suggest using the sum type as in the case of `proc getBuildableId*(self: Buildable | IconView | Spinner | EntryCompletion | Paned | AnyFilter | Box | CellAreaBox | Overlay | AboutDialog | ActionBar | ShortcutLabel | Viewport | Grid | GridView | ProgressBar | ShortcutController | EmojiChooser | Entry | PageSetupUnixDialog | SearchEntry | TreeExpander | AppChooserDialog | Dialog | FileFilter | EveryFilter | Text | ListBoxRow | ShortcutsGroup | ColorButton | FlowBox | Scale | DropDown | FontChooserWidget | FileChooserWidget | Label | FileChooserDialog | Stack | TreeViewColumn | PopoverMenuBar | Video | ComboBoxText | Picture | LinkButton | ConstraintLayout | Statusbar | Frame | StringList | CenterBox | MultiFilter | FontChooserDialog | CheckButton | CellView | MessageDialog | PasswordEntry | Calendar | Scrollbar | HeaderBar | SearchBar | ColumnView | ListBase | ToggleButton | ShortcutsWindow | DrawingArea | SpinButton | ScaleButton | TreeView | CellArea | Popover | ColorChooserDialog | ColorChooserWidget | StackSidebar | PrintUnixDialog | ShortcutsShortcut | ListStore | LockButton | ListView | ShortcutsSection | TreeStore | ComboBox | Fixed | TextTagTable | TextView | GLArea | AppChooserWidget | MultiSorter | MediaControls | Window | Notebook | Widget | SizeGroup | StackSwitcher | VolumeButton | Image | DragIcon | FontButton | AppChooserButton | Separator | ListBox | Expander | Button | PopoverMenu | EditableLabel | LevelBar | MenuButton | ScrolledWindow | Switch | Range | FlowBoxChild | InfoBar | Revealer | WindowControls | ApplicationWindow | AspectFrame | Assistant | WindowHandle): string =
`

**Comment by StefanSalewski** [comment]
>But StringList already implements ListModel interfase.

The problem may be the module boundaries. If I remember correctly the or types were automatically generated within the same module. I will try to investigate that soon.

**Comment by StefanSalewski** [comment]
Indeed we have converter procs which should avoid the ugly cast:

```
# module gtk4.nim
proc listModel*(x: gtk4.StringList): gio.ListModel = cast[gio.ListModel](x)
```

But unfortunately that does not work with latest devel compiler:

```nim
  var 
    sl = cast[ListModel](gtk4.newStringList("one", "two", "three", "four")) # we have a converter proc listModel()
    # sl = listModel(gtk4.newStringList("one", "two", "three", "four")) # generates a crash
    # ls = cast[ListModel](sl) # bad idea to create a new instance
    ns = gtk4.newNoSelection(sl) # (ls)
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
```

While it works with the plain cast, using converter proc listModel() generates a crash.

I think it was working with early ARC implementations, but I am not sure. I would guess that the converter proc generates a temporary copy, so that destroy() is called twice.

The reason why we need a cast or a converter proc is, that interfaces over module boundaries are involved, and that is not automatically handled by or types.

**Comment by StefanSalewski** [comment]
And I have to admit that I do not really understand why using the converter proc listModel() does not work here.

In the GTK3 examples we have file listview.nim with

let store = listStore(getModel(list))

where listStore() is also a converter proc and that works fine.

Maybe there is something very special with exactly this code example. As the example is not directly from the GTK core devs there may something be indeed special, maybe wrong?

**Comment by StefanSalewski** [comment]
Should be fixed, try

```
nimble uninstall gintro
nimble install gintro@#head
```
