### ISSUE TITLE
Two "getDefault" in "gdk"

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#13]
There are two "getDefault" in "gdk" with the following signatures:

```Nim
proc getDefault*(): Screen
proc getDefault*(): Keymap
```
I find this odd as Nim doesn’t allow the overloading by return type. So the compiler should have issued an error or am I missing something?

If this is legal, how can I specify the one I want to use?

**Comment by StefanSalewski** [comment]
```nim
var screen: Screen = getDefault()
```
may work. Will test tomorrow or ask Araq.

I have fixed the stupid get() and getDefault() proc names. It is now for example getDefaultScreen(). The stupid names came from gobject-introspection -- one has to now that name is stupid, and can append Class name. Will close this issue, please reopen if you find more stupid names.
