### ISSUE TITLE
simple ListView example from readme doesnt compile

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#132]
(17, 17) Error: undeclared identifier: 'gtk_tree_view_get_model'  
Did a new one here  https://github.com/StefanSalewski/gintro/pull/122/commits/40d582d1c4ed54130bab550cdfe83d3feee17135

**Comment by StefanSalewski** [comment]
>example from readme doesnt compile

From which readme? Is it from

https://github.com/StefanSalewski/gintro/blob/master/README.adoc

I don't think so.

**Comment by StefanSalewski** [comment]
And for me your example compiles with gintro 0.8.9 fine, with ARC and without.

So I have no idea what your issue may be.

**Comment by gavr123456789** [comment]
> > example from readme doesnt compile
> 
> From which readme? Is it from
> 
> https://github.com/StefanSalewski/gintro/blob/master/README.adoc
> 
> I don't think so.

Yes, this issue name is the name of example:  
```nim
import gintro/[glib, gobject, gtk]
import gintro/gio except ListStore

const
  LIST_ITEM = 0
  N_COLUMNS = 1

var list: TreeView

# this is copied from gtk.nim
#proc getModel*(self: TreeView): TreeModel =
#  new(result)
#  result.impl = gtk_tree_view_get_model(cast[ptr TreeView00](self.impl))

proc getListStore(self: TreeView): ListStore =
  new(result)
  result.impl = gtk_tree_view_get_model(cast[ptr TreeView00](self.impl))

proc appendItem(widget: Button; entry: Entry) =
  var
    val: Value
    iter: TreeIter
  let store = getListStore(list)
  let gtype = typeFromName("gchararray")
  discard gValueInit(val, gtype)
  gValueSetString(val, entry.text)
  store.append(iter)
  store.setValue(iter, LIST_ITEM, val)
  entry.text = ""

proc removeItem(widget: Button; selection: TreeSelection) =
  var
    ls: ListStore
    iter: TreeIter
  let store = getListStore(list)
  if not store.getIterFirst(iter):
      return
  if getSelected(selection, ls, iter):
    discard store.remove(iter)

proc onRemoveAll(widget: Button; selection: TreeSelection) =
  var
    iter: TreeIter
  let store = getListStore(list)
  if not store.getIterFirst(iter):
    return
  clear(store)

proc initList(list: TreeView) =
  let renderer = newCellRendererText()
  let column = newTreeViewColumn()
  column.title = "List Item"
  column.packStart(renderer, true)
  column.addAttribute(renderer, "text", LIST_ITEM)
  discard list.appendColumn(column)
  let gtype = typeFromName("gchararray")
  let store = newListStore(N_COLUMNS, cast[pointer]( unsafeaddr gtype)) # cast due to bug in gtk.nim
  list.setModel(store)

proc appActivate(app: Application) =
  let
    window = newApplicationWindow(app)
    sw = newScrolledWindow()
    hbox = newBox(Orientation.horizontal, 5)
    vbox = newBox(Orientation.vertical, 0)
    add = newButton("Add")
    remove = newButton("Remove")
    removeAll = newButton("Remove All")
    entry = newEntry()
  window. title = "List view"
  window.position = WindowPosition.center
  window.borderWidth = 10
  window.setSizeRequest(370, 270)
  list = newTreeView()
  sw.add(list)
  sw.setPolicy(PolicyType.automatic, PolicyType.automatic)
  sw.setShadowType(ShadowType.etchedIn)
  list.setHeadersVisible(false)
  vbox.packStart(sw, true, true, 5)
  entry.setSizeRequest(120, -1)
  hbox.packStart(add, false, true, 3)
  hbox.packStart(entry, false, true, 3)
  hbox.packStart(remove, false, true, 3)
  hbox.packStart(removeAll, false, true, 3)
  vbox.packStart(hbox, false, true, 3)
  window.add(vbox)
  initList(list)
  let selection = getSelection(list)
  connect(add, "clicked", listview.appendItem, entry)
  connect(remove, "clicked", listview.removeItem, selection)
  connect(removeAll, "clicked", listview.onRemoveAll, selection)
  showAll(window)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard run(app)

main()

```
(17, 17) Error: undeclared identifier: 'gtk_tree_view_get_model'  
  
> with ARC and without.

Its not about GC.

**Comment by gavr123456789** [comment]
> And for me your example compiles with gintro 0.8.9 fine  
  
My example is the new simple todo list for GTK 4.

**Comment by StefanSalewski** [comment]
I have no idea currently:

```
grep -C12 "gtk_tree_view_get_model" ~/.nimble/pkgs/gintro-0.8.9/gintro/gtk4.nim

proc gtk_tree_view_get_model(self: ptr TreeView00): ptr TreeModel00 {.
    importc, libprag.}

proc getModel*(self: TreeView): TreeModel =
  let gobj = gtk_tree_view_get_model(cast[ptr TreeView00](self.impl))
  if gobj.isNil:
    return nil
  let qdata = g_object_get_qdata(gobj, Quark)
  if qdata != nil:
    result = cast[type(result)](qdata)
    assert(result.impl == gobj)
  else:
    fnew(result, gtk4.finalizeGObject)
    result.impl = gobj
    GC_ref(result)
    discard g_object_ref_sink(result.impl)
    g_object_add_toggle_ref(result.impl, toggleNotify, addr(result[]))
    g_object_unref(result.impl)
    assert(g_object_get_qdata(result.impl, Quark) == nil)
    g_object_set_qdata(result.impl, Quark, addr(result[]))

```

Can you check if that proc is missing for your install for some reason?

**Comment by StefanSalewski** [comment]
Ah of course, gtk_tree_view_get_model() is not exported any more. It was years ago, but now we do not export the low level procs any more. Did you took the code directly from the readme file? Well I told you all in bold that you shall take the code only from the examples directory. And I really think there it is correct, as we test all the examples when we publish a releases. Well I should update the Readme too.

**Comment by StefanSalewski** [comment]
OK, I think we can close this. It should be clear that the code examples in the README file are for documentation purposes only, and the code from the examples directory should be used. We may update the code in the README file eventually, maybe next winter. Asciidoc allows inserting code from files directly in documents, but github does not support this currently. And generally it is easier to write documentation when we have a copy of the code example directly in the document as in an external file. But maybe we should indeed include external code when the documentation is written.

**Comment by gavr123456789** [comment]
Well, all I wanted to say here is that the example from the README can be updated. I also don't really understand why there is such a spread of material. There are many examples in the README (GTK 3), in the Examples folder (GTK 3 and 4), and in the book(GTK 4).  
  
Maybe we should get everything in order. I would suggest creating the README files in the Examples folder separately for GTK 4 and 3. Leaving the main README cleaner.

**Comment by gavr123456789** [comment]
I can do it in PR if you agree
