### ISSUE TITLE
Missing binding for gtk_dialog_new_with_buttons()

### ISSUE THREAD

**Issue by mildred** [StefanSalewski/gintro#140]
There is no way to call [gtk_dialog_new_with_buttons](https://developer.gnome.org/gtk4/stable/GtkDialog.html#gtk-dialog-new-with-buttons) which is required if you want to have buttons on your dialog window.

Trying to use `set_property("use-header-bar", to_int_val(1))` does not work:

>  GLib-GObject-WARNING **: 10:43:52.552: g_object_set_is_valid_property: construct property "use-header-bar" for object 'GtkDialog' can't be set after construction

**Comment by StefanSalewski** [comment]
Yes, gtk_dialog_new_with_buttons() is a varargs function which is not provided by default by gobject-introspection. We could try to provide it manually, but the varargs are generally not type safe unfortunately.

Are you sure that dialog.addButton() as used in

http://ssalewski.de/gtkprogramming.html#_dialog_box

does not work for your use case? addButton() is the general solution for language bindings.

If it does not work for you, then please try to point us to a minimal C code example that does exactly what you need, we will try to provide a substitute.

Note: Please do not try to use latest gintro@head, we have a serious issue currently. But current stable v0.9.2 should be fine for most use cases.

And please think carefully if you really intends to use GTK and gintro. Learning GTK is hard, Nim core devs favor fidget currently, and Rust has better GTK bindings :-)

**Comment by mildred** [comment]
Thank you, it was my mistake. `add_button` just works great if I do not call `dialog.add_child` but rather use `dialog.getContentArea.append()` as the example you linked suggested. I didn't know not all functions were part of gobject introspection.

Are you really trying to suggest Gtk shouldn't be used? I'm not opposed to the fact but I'd prefer writing my code in Nim and my target is definitely Linux.

**Comment by StefanSalewski** [comment]
>Are you really trying to suggest Gtk shouldn't be used?

I think I myself will continue using GTK. But only very few people do that. Nim GTK users seems to be less than a dozen after all these years, and for other programming languages the number is also very small. I was hoping that GTK4 would increase the number, but I think it did not. Who do really know GTK today? It is Mr. Bassi, maybe Mr. Larsen and Mr. Droege, and maybe some more. And which GTK apps appeared in the last 10 years? Some Rust apps, and the Horizon EDA tool written in GTKmm. Really not that much.

And Araq and some other Nim core devs seems to push fidget for Nim. I have no clue of fidget, seems to be something like Sketch or Figma where you just draw your GUI. Well may be OK for smartphone and web. For desktop apps I am not convinced. But of course GTK has the problem that it does not work for web, iphone and android. Well with libadwaita there is some mobile support now for the librem devices, but I never tried. And for the bindings I have to admit that Rust GTK bindings are better, they are close to Vala on lowest level, while gintro does not provide good low level support, i.e. creating new widgets from scratch that then can be used from other apps like native widgets. C, Vala, Rust supports that. I have spent 1600 hours on the gintro bindings already, I guess that I can not effort to spent much more time. We have considered hiring some Rust and GTK core devs to create perfect Nim bindings. But for that we may need about 50_000 Euro, which is hard without a sponsor. Well if we had 1000 serious users, each donating 50 Euro it may be possible. But with a dozen users?

**Comment by StefanSalewski** [comment]
>Note: Please do not try to use latest gintro@head,

Should be fixed, so you may try latest version with

```
gintro uninstall gintro
gintro install gintro@#head
```

**Comment by StefanSalewski** [comment]
Should be all fixed in v0.9.4 now.
Will close this issue, please reopen if necessary.
