### ISSUE TITLE
ListModel getNItems returns int instead of uint

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#149]
https://developer.gnome.org/gio/stable/GListModel.html#g-list-model-get-n-items  
I noticed this while I was rewriting the leaking example on Vala. Perhaps this is an error in the generation and there are still inconsistencies of this kind somewhere else.  
  
Here getNItems returns int, but g_list_model_get_n_items returns uint.
```nim
proc getNItems*(self: ListModel | ListStore): int =
  int(g_list_model_get_n_items(cast[ptr ListModel00](self.impl)))
```

**Comment by StefanSalewski** [comment]
Araq do not like uints.

I think a problem may occur when the number is larger than 2^31. Do you have a use case for so many items, or have you observed a real problem?

Nim generally uses ints and floats, so we do that for gintro when possible. An exception is when gtk uses int64, then we have to use int64 too as Nim's int may be 32 bit on 32 bit OS. Same for uint64.

**Comment by gavr123456789** [comment]
> Do you have a use case for so many items, or have you observed a real problem?

No, it's just that the first thing that came to my mind was that this is a generator error.  In fact, in reality, this can really become a problem with a large number of elements. What exactly is the use of using int instead of uint?  
  
> Araq do not like uints  
  
hehe, sounds strange

**Comment by StefanSalewski** [comment]
UInt has the wrap around behaviour, and substracting two uints can result in a negative value, which is not of uint type. Both is indeed a bit ugly. And mixing ints and uints in expressions is generally not a good idea at all, so avoiding uints seems to be a good idea.

But we can fix that for gintro, when you discover real issues.

**Comment by gavr123456789** [comment]
Okey, thank you for the explanation
