### ISSUE TITLE
"iterNChildren" shoud accept "nil" for "iter" arguments.

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#15]
This is the same problem already encountered for widgets, but for the TreeModel methods. "nil" is processed as as special case by the GTK library. There are several methods which use this trick.

For now, I will define an overloaded function.

**Comment by lscrd** [comment]
In fact, the situation is very different, and more complicated. The type "Iter" defines an object not a reference or a pointer to an object, so "nil" is not an acceptable value here.

I don’t know how manage this special case, but the interface of "gtk_tree_model_iter_n_children" is really ugly.

**Comment by StefanSalewski** [comment]
Yes, I did that by intent, I did it also for oldGTK3 low level wrapper. For simple structs like GdkColor or TextIter it makes sense to avoid a Nim proxy object. Those objects are generally advertised by gobject-introspection with marker user-alloc. The advantage when we use no proxy objects is, that we can allocate them simple on the stack like "var iter: TextIter", so we do not need "var iter = newTextIter()". And it saves a few bytes in executable. Passing to C library works fine because {.byRef.} pragma is applied, so Nim Compiler passes pointers, what is even the default. Handling nil is a bit complicated indeed, maybe we have to add overloaded procs manually indeed. Will continue tomorrow...

**Comment by StefanSalewski** [comment]
I tried to fix that with this minimal patch:

```
$ diff gen.nim ~/gintro/tests/
431,435d430
<     # ------------------
<     if isFunctionInfo(info) and (gFunctionInfoGetFlags(info).int and GIFunctionInfoFlags.WRAPS_VFUNC.ord) == 0:
<       if userAlloc and mayBeNil:
<         str.add(" | ptr " & str & " = nil")
<     # ------------------

```

Now we have something like
```nim
proc gtk_text_iter_backward_search*(self: TextIter; str: cstring; flags: TextSearchFlags; 
    matchStart: var TextIter; matchEnd: var TextIter; limit: TextIter | ptr TextIter = nil): gboolean {.
    importc: "gtk_text_iter_backward_search", libprag.}
```

So it should be possible to pass a nil pointer or nothing instead of a textiter when gobject-introspection allows NULL. I hope this work, have no code for testing currently.

**Comment by lscrd** [comment]
It doesn’t work in my program. I have written a small test. The first call to "iterNChildren" compiles, of course, but there is still an error in the second one.

```Nim
import gintro/[gtk, gobject, glib]

proc p(model: TreeModel, iter: TreeIter) =
  discard model.iterNChildren(iter)

proc q(model: TreeModel) =
  discard model.iterNChildren(ptr TreeIter(nil))
```

**Comment by StefanSalewski** [comment]
Interesting, thanks. I think I have to ask Araq.

iter: TreeIter | ptr TreeIter = nil

seems to generate some headache for the compiler.

**Comment by StefanSalewski** [comment]
```nim
#The problem seems to be the = nil
# But that is what we want -- we want to pass an TreeIter or nil

type
  TreeIter* {.pure, byRef.} = object
    stamp*: int32

  TreeModel* = ref object of RootObj

proc iterNChildren*(self: TreeModel; iter: TreeIter | ptr TreeIter = nil): int =
  discard

var model: TreeModel
var iter: TreeIter

discard iterNChildren(model, iter)

# yyy.nim(14, 22) template/generic instantiation from here
# yyy.nim(8, 70) Error: type mismatch: got (nil) but expected 'TreeIter = object'
```

**Comment by lscrd** [comment]
Yes, removing "= nil" makes it compile, but to pass "nil", we have to write "(ptr TreeIter)(nil)". Not very elegant.

Using an overloaded procedure may work, I suppose.

Another way to manage this would be to define some "null" TreeItem object for the high level interface which would be translated as "nil" when calling the low level interface. I have no idea what could be such a "null" TreeItem, though.

I understand the reason to use "object" rather than pointer here. It is also he way TreeIter is defined in the GTK3 interface (as a struct), but the strong typing in Nim makes it complicated to manage here.

I have to leave for two days. I will work on my programs again probably on Thursday. Bye.

**Comment by StefanSalewski** [comment]
Yes an overloaded proc seems to be necessary for this case.

I will try to fix all the open bugs in the next days, bye. Well, except the signal emission, that will take longer.

**Comment by StefanSalewski** [comment]
Closing with this patch applied:
```
$ diff tests/gen.nim ~/gitest/tests/gen.nim
434c434,437
<         str.add(" | ptr " & str & " = nil")
---
>         #str.add(" | ptr " & str & " = nil")
>         var h = str
>         if h.startsWith("var "): h = h[4 .. ^1]
>         str.add(" = cast[ptr " & h & "](nil)[]")

```

Now this compiles:

```nim
import gintro/[gtk, gobject, glib]

proc p(model: TreeModel, iter: TreeIter) =
  discard model.iterNChildren(iter)

proc q(model: TreeModel) =
  discard model.iterNChildren()
```

A bit strange is it for var parameters, we have only very few like

```
pango.nim:proc transformRectangle*(self: Matrix; rect: var Rectangle = cast[ptr Rectangle](nil)[]) =
```

**Comment by lscrd** [comment]
It works fine. But, if we want to pass explicitely "nil", we have to use "cast[ptr TreeIter](nil)[]" which is awful. We don’t need to do that, of course, but somebody who looks at the GTK3 documentation may think it is the way to go. It is something which will have to be documented.

**Comment by StefanSalewski** [comment]
Great that it works. Yes we have to document how it is used. That nil default does not work is indeed a known bug:

https://github.com/nim-lang/Nim/issues/1201
