### ISSUE TITLE
Doing wrapper wrong?

### ISSUE THREAD

**Issue by juancarlospaco** [StefanSalewski/gintro#153]
@StefanSalewski
I am opening this issue, but is NOT a bug, 
I open an issue because the repo has no "Discussions" enabled, sorry.

I do not have much experience with GTK. 
But I was thinking this info may be relevant to you.
[I understand from your readme that the wrapper is done manually (c2nim, manual editing).](https://github.com/StefanSalewski/gintro#current-state-of-these-bindings)

So I was chill watching some random Twitch streams about coding, 
the topic of programming languages GTK wrappers come up,
the streamer has a lot of experience in C, C++, GTK, wrappers, etc etc,
your repo come up for "Nim GTK" in the web search live on stream.

Important part: **Looks like you are doing the wrapper wrong** (?)
according to him theres a much better easy automatic way:

- https://www.twitch.tv/videos/1085639644?t=02h30m

Please watch the video maybe that info is useful to you.
Feel free to close if info is useless.
Twitch Videos are deleted after 15 days.
😃

**Comment by StefanSalewski** [comment]
Sorry, I do not intent to watch that bullshit.

> Twitch Videos are deleted after 15 days.

Great!

**Comment by juancarlospaco** [comment]
I agree, I should be contributing/pull-requesting/donating to other projects instead. 🙂:+1:
