### ISSUE TITLE
What type of arg we getting in CClosure callback

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#163]
I keep trying to solve https://github.com/StefanSalewski/gintro/issues/157.   
FileInfo has no properties, so I need a CClosureExpression to get fileName from it.  

So I found some C () and Vala(https://github.com/aeldemery/gtk4_dropdown/blob/master/src/MainWindow.vala#L45, https://github.com/aeldemery/gtk4_color_list/blob/80fdf65c35bc3fa3817a47502519d5c2b38508e5/src/MainWindow.vala#L217 ) examples with CClosureExpression and tryed to make the same thing in Nim.   
Here my try:  
```nim
import gintro/[gtk4, gobject, gio]
import std/with

proc getFileName(info: gio.FileInfo): string =
  return info.getName()  

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(newLabel(""))
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  let 
    lb = listitem.getChild().Label
    fileobj = cast[FileInfo](listitem.getItem())
  
  lb.text = fileobj.getFileName()

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  # There's nothing to do here. 
  # If you does something like setting a signal in bind_cb,
  # then disconnecting the signal is necessary in unbind_cb. 
  echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild (nil)
  # When the child of listitem is set to NULL, the reference to GtkLabel will be released and lb will be destroyed. 
  # Therefore, g_object_unref () for the GtkLabel object doesn't need in the user code. 

proc entryChanged(self: EntryBuffer, position: int, chars: string, nChars: int) = 
  echo self.text

proc callback(fileInfo: FileInfo): string {.cdecl.} = 
  debugEcho fileInfo != nil
  result = "qwe"
  # result = fileInfo.getFileName()

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
    file = gio.newGFileForPath(".")
    dl = gtk4.newDirectoryList("standard::*", file)
    ls = listModel(dl)
    ss = newStringSorter()
    fm = newSortListModel(ls, ss)
    ns = gtk4.newNoSelection(listModel(fm))
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)

    mainBox = newBox(Orientation.vertical, 5)
    patternEntry = newEntry()


  patternEntry.placeholderText = "Enter pattern"
  patternEntry.buffer.connect("inserted_text", entryChanged)



  with mainBox:
    append patternEntry
    append scr
  # let gFileType = typeFromName("GFileInfo")
  # let gStringType = typeFromName("GFileInfo")

  # ss.expression = newPropertyExpression(gFileType, nil, "display-name" )
  ss.expression = newCClosureExpression(g_string_get_type(), nil, 0, nil, cast[Callback](callback), nil, nil)

  with scr: 
    vexpand = true
    setChild lv

  dl.setMonitored true

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    defaultSize = (600, 400)
    title = "Nim ListView"
    setChild mainBox
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()
```
It crushes in 2 ways: 
1) if `callback` func returns string then it crush with `double free or corruption (out)`  
2) if `callback` func returns cstring then with `free(): invalid pointer`  
  
If result = nil in `callback` func, then we can see `GLib-CRITICAL **: 03:26:20.072: g_utf8_casefold: assertion 'str != NULL' failed`  
Thats mean result must be an UTF 8 text.

**Comment by gavr123456789** [comment]
Just found this, so it need return string from g_strdup  
https://gitlab.gnome.org/GNOME/gtk/-/blob/master/testsuite/gtk/expression.c#L162  
Now no crash, but I still cant get the FileInfo from args. I see its not nil == true, but any call to in is crash with `Attempt to read from nil?`   
Im not sure what kind of type Im getting there, may be its ptr to FileInfo.

**Comment by StefanSalewski** [comment]
Thanks for reporting, I will try to investigate the issue.

In the last two weeks I have worked a bit on one of my own GTK tools, see

https://github.com/StefanSalewski/SDT

The final goal is a simple CAD and EDA tool. I started a similar tool in Ruby in 2010, and that tool was the main reason why I came to Nim in 2014. But I had too less time to work on a Nim version all the years unfortunately.

I have to admit that I have still no idea what type of program you finally intent to create.

For the callbacks with user functions that return a string Mr. Dankr4d discovered the problems already some weeks ago. I had the feeling that we fixed it in #head. I really should learn more GTK4 and maybe continue with the GTK4 Nim book, but I am not sure if I will have time for that in next winter.

**Comment by StefanSalewski** [comment]
Well seems to be obvious that your code can not work:

```
proc callback(fileInfo: FileInfo): cstring {.cdecl.} = 

$ grep -C2 "FileInfo\* =" ~/.nimble/pkgs/gintro-#head/gintro/gio.nim 

type
  FileInfo* = ref object of gobject.Object
  FileInfo00* = object of gobject.Object00
```

When you go the low level dirty path, which {.cdecl.}  implies, you have to use only the low level data types. I assume that your proc called callback is called directly by GTK, with no trampoline involved. Then you are right, it should return a cstring allocated by g_strdup. But it also receives a low level Fileinfo, which is called FileInfo00 in gintro :-)

Hope that info helps you. Have you made some progress in writing macros? Araq generally do not like my macros, as my macros are mostly text based. But I have still to learn how to write macros only by using AST functions.

**Comment by StefanSalewski** [comment]
Here is the basic shape how the low level proc may look.

```nim
proc callback(fileInfo: ptr FileInfo00): cstring {.cdecl.} = 
  debugEcho fileInfo != nil
  #result = g_strdup("test")
  var f = new FileInfo
  f.impl = fileInfo
  f.ignoreFinalizer = true # fast hack, we would use a {.global.} var in the macro. Or maybe do in a other way?
  result = g_strdup(f.getFileName())
  echo result
```

Of course that is very dirty, you may look at the existing macros of gintro to learn how one can handle the allocation of the proxy object. Generally we do it with a {.global.} which we allocate only once, but maybe better solutions exists. I have still no idea what your example program shall do, but with above fix I get at startup

```
 ./t
true
t
true
t.nim
unbind
unbind
```

So maybe not that wrong.

**Comment by gavr123456789** [comment]
@StefanSalewski yes, I already tryed this, before your last message  
Here working version  
```nim
import gintro/[gtk4, gobject, gio, glib]
import std/with

proc getFileName(info: gio.FileInfo): string =
  return info.getName()  

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(newLabel(""))
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  let 
    lb = listitem.getChild().Label
    fileobj = cast[FileInfo](listitem.getItem())
  
  lb.text = fileobj.getFileName()

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild (nil)

proc entryChanged(self: EntryBuffer, position: int, chars: string, nChars: int) = 
  echo self.text

proc callback(fileInfo: ptr FileInfo00): cstring {.cdecl.} = 
  result = g_file_info_get_attribute_string(fileInfo, "standard::display-name")

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
    file = gio.newGFileForPath(".")
    dl = gtk4.newDirectoryList("standard::*", file)
    ls = listModel(dl)
    ss = newStringSorter()
    fm = newSortListModel(ls, ss)
    ns = gtk4.newNoSelection(listModel(fm))
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)

    mainBox = newBox(Orientation.vertical, 5)
    patternEntry = newEntry()


  patternEntry.placeholderText = "Enter pattern"
  patternEntry.buffer.connect("inserted_text", entryChanged)



  with mainBox:
    append patternEntry
    append scr
  # let gFileType = typeFromName("GFileInfo")
  # let gStringType = typeFromName("GFileInfo")

  # ss.expression = newPropertyExpression(gFileType, nil, "display-name" )
  ss.expression = newCClosureExpression(g_string_get_type(), nil, 0, nil, cast[Callback](callback), nil, nil)

  with scr: 
    vexpand = true
    setChild lv

  dl.setMonitored true

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    defaultSize = (600, 400)
    title = "Nim ListView"
    setChild mainBox
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()
```
To do this, I had to make the function `g_file_info_get_attribute_string` public, so this wont work on clear gintro install

**Comment by StefanSalewski** [comment]
>I had to make the function g_file_info_get_attribute_string public,

Yes of course, we have to write macros for that stuff. I am not sure how much we really need, I once counted async functions, I think that was already 150, so we may need totally a few hundred macros. And all of them are a bit different, I assume that we have to write all of them manually. For only three active users :-(

**Comment by gavr123456789** [comment]
@StefanSalewski, just updated that, yea,   
So, we need some kind of mechanism for such cases when GTK returns its pure objects to us. Temporarily, it can be a function that converts a 00 object to a regular one.

**Comment by gavr123456789** [comment]
> For only three active users  
  
I think we should make a simple application and put it on flathub(there one on Crystal https://github.com/gavr123456789/GTK-info/blob/master/SHOWCASE.MD#crystal), as well as popularize gintro in nim chats(https://t.me/nim_lang/73331).

**Comment by StefanSalewski** [comment]
It is very hard. I had some hope that with GTK4 the general popularity would increase, but that did not happen. And for Nim we have 20 GUI toolkits now, and Araq and some other devs are pushing fidget. And the Nim core devs do not support gintro at all. I put https://github.com/StefanSalewski/SDT to github to have one more example -- I would guess that such a tool is still not possible with the other 19 Nim GUI kits. But for most users toy apps seems enough. And well, GTK is hard to learn and it does not support Android and Windows not really well. So I can understand that most people do not want to use it.

**Comment by gavr123456789** [comment]
@StefanSalewski 
> I have to admit that I have still no idea what type of program you finally intent to create.  
  
  
https://github.com/gavr123456789/Katana  
I already started 2 mouth ago. This is a browser of tree-like data structures, but so far it is exclusively a file browser with a non-standard approach.  
  
Here demo where you can see core ideas. 

https://user-images.githubusercontent.com/30507409/127356032-8190bd69-e083-49c6-850f-892ccb63b54c.mp4

**Comment by gavr123456789** [comment]
> I would guess that such a tool is still not possible    
  
I recommend trying the other frameworks to understand that they are not capable of anything, there is not even one percent of the GTK capabilities, I tried fidget and nimgui.  
Even if we assume that there is enough functionality, they will still not have enough performance optimization, ListApi GTK4 scales to infinity, since it reuses already created elements, which in total will never exceed 200, GTK itself uses a GPU for rendering on all platforms, and a new universal NGL renderer has recently been released. Also in GTK 4, a new render model based on trees, only individual nodes are redrawn when changes are made.  And the last thing is infostructure that gnome has for gtk, its debuger that can be run on any GTK 4 app with ctrl shift d
![image](https://user-images.githubusercontent.com/30507409/127388738-d45230dd-2479-4d89-bd89-22841220614a.png)
GSettings(that using which use different native tools on each platform, for example, the registry on Windows, dconf on Linux), GResources(Compiles data in binary С files, compressing XML.)
It is very unlikely that the new frameworks will be comparable to GTK, a large team of experienced developers is needed, especially since GTK itself continues to develop by doing new things like LibAdwaita.
