### ISSUE TITLE
Check that GC works 

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#165]
I just tried to run the application with gc none and found that it leaks exactly the same as with the rest of the gc. I think we need to create some simple test applications to make sure that gc works with gtk. For example, an application that adds and removes a button on the screen(or 100 buttons).  
Also test the memory is cleared when using legacy widgets.

**Comment by StefanSalewski** [comment]
I think that the GC works because I got a few crashes when GC freed memory which it should not free :-)

But that task is hard. You may know that GTK often does not free its internally used memory, but uses the fact that all memory of a executed program is freed when the program terminates. That makes use of valgrind very difficult -- one can use some form of whitelists. Valgrind reports leaks by default for all the C code examples of the GTK devs, and often other errors. There was a discussion on the Gnome forum recently.

For ARC gintro has an option like -d:gintroDebug that let destructors echo to the terminal. And there should be one test program in the examples that test destructor use.

For my own programs I have never noticed a really large or continued increasing RAM usage, so I never have really investigated this topic.

**Comment by StefanSalewski** [comment]
And you can compile with --expandArc to see where destructors get called.

**Comment by gavr123456789** [comment]
Ye, also I added GC_getStatistics.

**Comment by gavr123456789** [comment]
https://user-images.githubusercontent.com/30507409/128937028-c463ba15-4d0b-4e3d-b368-1ce31e4a9c17.mp4



@StefanSalewski Memory leak is still my biggest pain. I noticed that simply changing the number of elements in one ListView in my application is already a memory leak, which means that the elements are being released incorrectly. I still don't understand why in the teardown child callback, the sheet item comes with a zero value(as if there is nothing left to release).   
  
But I had an idea, each element of the list I have is the following object:  
```nim
type 
  FileRow* = ref object of Stack 
    info*: gio.FileInfo
    fullPath*: string
    btn1*: ToggleButton
    btn2*: ToggleButton
    backBtn*: Button
    image*: Image
    labelFileName*: Label
    pageNum*: int
    # signals
    arrowBtnSignalid*: uint64
    fileBtnSignalid*: uint64 
    switchStackBtnSignalid*: uint64 
```  
  
It seems to me that there is a possibility that these links remain unreleased, is there a way to define them here as weak links? And does it make sense when using ref GC?

**Comment by gavr123456789** [comment]
I remaked this in to tiny minimal example, where all items are just buttons, and I think there no leak(or almost no leak):  

https://user-images.githubusercontent.com/30507409/128937895-eca655e1-5711-4901-96f3-58d736c23178.mp4

So Im sure the problem is in inheritance.  
  
 ```nim
import gintro/[gtk4, gobject, gio]
import std/with

# Factory signals
proc getFileName(info: gio.FileInfo): string =
  return info.getName()  

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(newButton(""))
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  let 
    lb = listitem.getChild().Button
    strobj = cast[FileInfo](listitem.getItem())

  lb.label = strobj.getFileName()

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  discard
  # echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  echo listitem.child == nil
  listitem.setChild (nil)


proc entryChanged(entry: SearchEntry, fm: FilterListModel) = 
  let ff = newFileFilter()
  if entry.text != "":
    ff.addPattern("*" & entry.text & "*")
    fm.setFilter(ff)
  else:
    ff.addPattern("*")
    fm.setFilter(ff)
  echo entry.text

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
    file = gio.newGFileForPath(".")
    dl = gtk4.newDirectoryList("standard::*", file)
    ls = listModel(dl)
    ff = newFileFilter()
    fm = newFilterListModel(ls, ff)
    ns = gtk4.newNoSelection(listModel(fm))
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
    header = newHeaderBar()
    searchButton = newToggleButton()
    mainBox = newBox(Orientation.vertical, 5)
    hbox = newBox(Orientation.horizontal, 5)

    patternEntry = newSearchEntry()

    searchBar = newSearchBar()

  searchButton.setIconName("system-search-symbolic")
  discard searchButton.bindProperty("active", searchBar, "search-mode-enabled", {bidirectional})
  header.packEnd searchButton

  ff.addPattern("*")

  patternEntry.connect("search-changed", entryChanged, fm)
  patternEntry.halign = Align.center

  with searchBar:
    connectEntry patternEntry
    showCloseButton = false
    child = patternEntry
    keyCaptureWidget = window

  with scr: 
    hexpand = true
    vexpand = true
    setChild lv

  hbox.append scr
  
  with mainBox:
    append searchBar
    append hbox

  dl.setMonitored true

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    titlebar = header
    child = mainBox
    title = "Nim ListView"
    defaultSize = (600, 400)
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()


 ```   
   
The most interesting part is `echo listitem.child == nil` that always show true in the every search iteration.

**Comment by StefanSalewski** [comment]
For the leaks I recently learned that /usr/bin/time -v does not report the true value for Nim, see

https://forum.nim-lang.org/t/8310

I am using valgrind now. So some of my own tests may have been wrong in the past. I am working on making cairo drawing leak free even without manually memory management, and I made some good progress.

**Comment by gavr123456789** [comment]
https://user-images.githubusercontent.com/30507409/130324573-2cd08b90-c068-44b6-a6cc-d9c84ec21b34.mp4

Tested with this program  
Each widget there is a inherits Box and contains links to other widgets, including images. As you can see, the RAM consumed grows up to a certain point(35 MB) and then stops.   
```nim
import gintro/[gtk4, gobject, gio, pango, glib]
import std/with

type
  Row = ref object of Box
    btn1: Button
    btn2: Button
    label: Label
    image*: Image


proc createRow(): Row =
  let 
    row = newBox(Row, Orientation.horizontal, 0)
  row.btn1 = newButton()
  row.btn2 = newButton()
  row.label = newLabel()
  row.image = newImage()
  row.label.wrap = true
  row.label.wrapMode = pango.WrapMode.char
  row.label.maxWidthChars = 15

  row.cssClasses = "linked"

  row.image.setFromIconName("QtIcon-symbolic")
  
  row.btn1.child = row.label
  row.append row.image
  row.append row.btn1
  row.append row.btn2
  result = row
  echo "row created"


# Factory signals
proc getFileName(info: gio.FileInfo): string =
  return info.getName()  

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(createRow())
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  let 
    row = listitem.getChild().Row
    strobj = cast[FileInfo](listitem.getItem())

  row.label.text = strobj.getFileName()

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  discard
  # echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  echo listitem.child == nil
  listitem.setChild (nil)


proc entryChanged(entry: SearchEntry, fm: FilterListModel) = 
  let ff = newFileFilter()
  if entry.text != "":
    ff.addPattern("*" & entry.text & "*")
    fm.setFilter(ff)
  else:
    ff.addPattern("*")
    fm.setFilter(ff)
  echo entry.text

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
    file = gio.newGFileForPath(".")
    dl = gtk4.newDirectoryList("standard::*", file)
    ls = listModel(dl)
    ff = newFileFilter()
    fm = newFilterListModel(ls, ff)
    ns = gtk4.newNoSelection(listModel(fm))
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
    header = newHeaderBar()
    searchButton = newToggleButton()
    mainBox = newBox(Orientation.vertical, 5)
    hbox = newBox(Orientation.horizontal, 5)

    boolFilter = newBoolFilter()


    patternEntry = newSearchEntry()

    searchBar = newSearchBar()

  searchButton.setIconName("system-search-symbolic")
  discard searchButton.bindProperty("active", searchBar, "search-mode-enabled", {bidirectional})
  header.packEnd searchButton

  ff.addPattern("*")

  patternEntry.connect("search-changed", entryChanged, fm)
  patternEntry.halign = Align.center

  with searchBar:
    connectEntry patternEntry
    showCloseButton = false
    child = patternEntry
    keyCaptureWidget = window

  with scr: 
    hexpand = true
    vexpand = true
    minContentWidth = 240
    setPropagateNaturalWidth true
    setChild lv

  hbox.append scr
  
  with mainBox:
    append searchBar
    append hbox

  dl.setMonitored true

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    titlebar = header
    child = mainBox
    title = "Nim ListView"
    defaultSize = (600, 400)
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()

```  
  
This was compiled with ref gc and release. Here ARC version:  

https://user-images.githubusercontent.com/30507409/130324935-4f42c598-82e1-44b0-851e-c1766c1ecb10.mp4

And how we can see it leaks hard. ORC same results

**Comment by gavr123456789** [comment]
Hmm, same program but without custom type has same leak with ARC/ORC and no leak with ref gc
```nim
import gintro/[gtk4, gobject, gio, pango, glib]
import std/with

proc createRow(): Box =
  let 
    row = newBox(Box, Orientation.horizontal, 0)
    btn1 = newButton()
    btn2 = newButton()
    label = newLabel()
    image = newImage()

  label.wrap = true
  label.wrapMode = pango.WrapMode.char
  label.maxWidthChars = 15

  row.cssClasses = "linked"

  image.setFromIconName("QtIcon-symbolic")
  
  btn1.child = label
  row.append image
  row.append btn1
  row.append btn2
  result = row
  echo "row created"


# Factory signals
proc getFileName(info: gio.FileInfo): string =
  return info.getName()  

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(createRow())
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  let 
    row = listitem.getChild()
    strobj = cast[FileInfo](listitem.getItem())
    btn1 = row.lastChild.Button

  btn1.label = strobj.getFileName()

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  discard
  # echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  echo listitem.child == nil
  listitem.setChild (nil)


proc entryChanged(entry: SearchEntry, fm: FilterListModel) = 
  let ff = newFileFilter()
  if entry.text != "":
    ff.addPattern("*" & entry.text & "*")
    fm.setFilter(ff)
  else:
    ff.addPattern("*")
    fm.setFilter(ff)
  echo entry.text

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()
    file = gio.newGFileForPath(".")
    dl = gtk4.newDirectoryList("standard::*", file)
    ls = listModel(dl)
    ff = newFileFilter()
    fm = newFilterListModel(ls, ff)
    ns = gtk4.newNoSelection(listModel(fm))
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
    header = newHeaderBar()
    searchButton = newToggleButton()
    mainBox = newBox(Orientation.vertical, 5)
    hbox = newBox(Orientation.horizontal, 5)
    patternEntry = newSearchEntry()
    searchBar = newSearchBar()

  searchButton.setIconName("system-search-symbolic")
  discard searchButton.bindProperty("active", searchBar, "search-mode-enabled", {bidirectional})
  header.packEnd searchButton

  ff.addPattern("*")

  patternEntry.connect("search-changed", entryChanged, fm)
  patternEntry.halign = Align.center

  with searchBar:
    connectEntry patternEntry
    showCloseButton = false
    child = patternEntry
    keyCaptureWidget = window

  with scr: 
    hexpand = true
    vexpand = true
    minContentWidth = 240
    setPropagateNaturalWidth true
    setChild lv

  hbox.append scr
  
  with mainBox:
    append searchBar
    append hbox

  dl.setMonitored true

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    titlebar = header
    child = mainBox
    title = "Nim ListView"
    defaultSize = (600, 400)
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()

```

**Comment by StefanSalewski** [comment]
>, the RAM consumed grows up to a certain point(35 MB) and then stops.

From my understanding a real leak continues to consume RAM. When it automatically stops at some point it is not really a leak for me.

I recently tuned the drawingarea example, which also applies to my SDT CAD program: Before it really leaked infinite when we commented out the manual destroy() calls. Now we can comment out the destroy calls and it works fine. Very fine for ARC. Not that fine for default refc GC. The refc GC waits until about 3 GB are consumed, and then frees the 3 GB. That continues, as the default GC is lazy. But the cairo library contains many functions which I have not yet tested.

For your 35 MB leak: We would have to create a C or Vala program which leaks much less, and then investigate.

Have you seen  https://github.com/nim-lang/Nim/issues/18698 ? So in the future we will not be able to use cstrings any more :-(

**Comment by gavr123456789** [comment]
> From my understanding a real leak continues to consume RAM. When it automatically stops at some point it is not really a leak for me.

Its now leak for me too.  
> has same leak with ARC/ORC and no leak with ref gc

**Comment by gavr123456789** [comment]
> The refc GC waits until about 3 GB are consumed, and then frees the 3 GB. That continues, as the default GC is lazy  

Did `GC_fullCollect` helps?

**Comment by StefanSalewski** [comment]
Yes, GC_fullCollect() should help, but it is intended for use in debugging only, not in final programs. There exists another proc which runs the default GC for a small time period, I guess that would help too. But I really know too less about the default GC, and I guess asking Araq makes not much sense as he do not like GTK that much. I was already surprised that he reacted friendly to my cstrings issue. And well, generally people can use ARC now.

**Comment by StefanSalewski** [comment]
>same leak with ARC/ORC and no leak with ref gc

With refc GC you may just not see the leaks, see this thread

https://forum.nim-lang.org/t/8300

With --gc:arc -d:useMalloc valgrind generally reports that about 25 MB may possible be lost, but that value does not increase for me when I run the program for a longer time. So that 25 MB is not really important for me, maybe that memory is consumed by Nim or GTK internally.

**Comment by gavr123456789** [comment]
ye, GC works with inherited from gtk classes objects
