### ISSUE TITLE
Question regarding the gtk3 cairo_anim.nim example and drawingAreaDrawCb

### ISSUE THREAD

**Issue by ffwqo** [StefanSalewski/gintro#174]
I have been trying to port the gnome gtk4 c examples to nim and have been stuck at figuring out how to use cairo with nim. I was wondering how drawingAreaDrawCb gets its context parameter from the connect method. Its called like 
```nim
connect(drawingArea, "draw", drawingAreaDrawCb)
```
with the definition 
```nim
proc drawingAreaDrawCb(widget: DrawingArea; context: Context): bool =
```
in cairo_anim.nim . I was thinking of simply using the native surface from window and passing that as a surface and create a new context via cairo.newContext but that didn't work.
It does compile and run but if you change gtk to gtk4 in the import statement one gets a type mismatch error. 
```nim
~/.choosenim/toolchains/nim-1.4.8/lib/core/macros.nim(559, 20) Error: type mismatch: got <DrawingArea>
but expected one of: 
proc drawingAreaDrawCb(widget: DrawingArea; context: Context): bool
  first type mismatch at position: 2
  missing parameter: context

expression: drawingAreaDrawCb(cast[gtk4.DrawingArea](h))
```
Any ideas on how to fix this? Here is my code I didn't change much apart from the gtk->gtk4 in import and window.showAll -> window.show
```nim
import gintro/[gtk4, glib, gobject, gio, cairo]
import math

const
  NumPoints = 1000
  Period = 100.0

proc invalidateCb(w: Widget): bool =
  queueDraw(w)
  return SOURCE_CONTINUE

proc sineToPoint(x, width, height: int): float =
  math.sin(x.float * math.TAU / Period) * height.float * 0.5 + height.float * 0.5

proc drawingAreaDrawCb(widget: DrawingArea; context: Context): bool =
  var redrawNumber {.global.} : int
  let width = getAllocatedWidth(widget)
  let height = getAllocatedHeight(widget)
  for i in 1 ..< NumPoints:
    context.lineTo(i.float , sineToPoint(i + redrawNumber, width, height))
  context.stroke
  inc(redrawNumber)
  return true # TRUE to stop other handlers from being invoked for the event. FALSE to propagate the event further.

proc appActivate(app: Application) =
  let window = newApplicationWindow(app)
  window.title = "Drawing example"
  window.defaultSize = (400, 400)
  let drawingArea = newDrawingArea()
  window.setChild(drawingArea)
  window.show()
  discard timeoutAdd(1000 div 60, invalidateCb, drawingArea)
  drawingArea.connect("draw", drawingAreaDrawCb)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard run(app)

main()
```

**Comment by StefanSalewski** [comment]
We have multiple examples for use of cairo with GtkDrawingArea:
ls -1 ~/gintro/examples/gtk3/
cairo_anim.nim
darea_test.nim
drawingarea.nim
simpledrawingarea.nim

A GTK4 example is

https://github.com/StefanSalewski/SDT


simpledrawingarea.nim and drawingarea.nim should be a good start, sdt.nim shows you the changes for GTK4.

When my memory is right, for GTK4 there was a setdrawFunc introduced,

```$ grep setDrawFunc ~/.nimble/pkgs/gintro-#v0.9.2/gintro/*
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:proc setDrawFunc*(self: DrawingArea; drawFunc: DrawingAreaDrawFunc;
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:macro msetDrawFunc(da: DrawingArea; p: untyped; arg: typed; ignoreArg: bool): untyped =
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:template setDrawFunc*(da: DrawingArea; p: untyped; arg: typed): untyped =
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:  msetDrawFunc(da, p, arg, false)
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:template setDrawFunc*(da: DrawingArea; p: untyped): untyped =
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gimplgtk.nim:  msetDrawFunc(da, p, "", true)
/home/salewski/.nimble/pkgs/gintro-#v0.9.2/gintro/gtk4.nim:proc setDrawFunc*(self: DrawingArea; drawFunc: DrawingAreaDrawFunc;
```

which replaced the use of the "draw" signal from GTK3:

```
$ grep "\"draw" ~/gintro/examples/gtk3/simpledrawingarea.nim 
  da.connect("draw", drawingAreaDrawCb, result)
```

So indeed I think you have to consult the sdt.nim example for that detail. I can currently not remember if the GTK4 Nim book already contains another GtkDrawingArea example, I guess not yet.

I think that should be enough info for you when you have some basic Nim and GTK understanding already.

Let me know if you should need more help.

Finally a warning: GTK generally and gintro for Nim is not very popular, and learning GTK is hard. So if you are new to GTK and Nim, you may favour other GUI toolkits, Araq is mostly advertising fidget now.

**Comment by StefanSalewski** [comment]
Ah wait, there is also

salewski@nuc ~/SDTold $ less ~/GtkProgrammingBook/nim/drawing.nim 
salewski@nuc ~/SDTold $ less ~/GtkProgrammingBook/nim/scribble0.nim

I guess at least one of that apps should work, but I have not yet described them in the book text.

**Comment by StefanSalewski** [comment]
Well I assume you left, so I will close this issue for now. Please reopen in case you should come back and need more help.
