### ISSUE TITLE
couldnot load libgtk-3.0.dll

### ISSUE THREAD

**Issue by kalbhairab** [StefanSalewski/gintro#175]

**Comment by StefanSalewski** [comment]
I assume that you are the same Mr. Kalbhairab from the Nim Forum?

So gintro is definitely not the right choice for you, better use one of the other 20 available Nim GUI toolkits.

**Comment by kalbhairab** [comment]
ok

**Comment by kalbhairab** [comment]
this may be off topic but cant we use webview from nimview to make gui in nim using html and css which look nice gui. Also if we use html then will it reduce performance?

**Comment by StefanSalewski** [comment]
I don't know, please ask on Nim Forum. I have listed the names of 20 other NimGUI Toolkits at the start of the GTK4 Nim book, see  http://ssalewski.de/gtkprogramming.html. One of these may provide what you need, but I don't know which.
