### ISSUE TITLE
[question] how to avoid type errors with child classes/objects?

### ISSUE THREAD

**Issue by ITwrx** [StefanSalewski/gintro#182]
Please forgive the disturbance, but it seems i'm not understanding something fundamental about using gintro. I'm trying to get a rtsp stream into my gtk4 gui and the gnome discourse has helpfully advised me to: 

> You would have to use a file object with a URI, not a filename. The media stream can then be attached to a GtkVideo with set_media_stream, or to a GtkPicture with set_paintable.

[link to gnome discourse thread](https://discourse.gnome.org/t/rtsp-stream-s-to-gtk4-grid/7739/12)

so i've tried both with:

#latest, quick gtk Picture attempt.
```
let media_file1 = gtk4.newMediaFileForFile(gio.newGFileForUri("rtsp://admin:5uzQM8V3XSbrYUq6@192.168.43.5:554//h264Preview_01_sub"))
  let paintable1 = gtk4.setPaintable(media_file1)
  let video1 = gtk4.newPicture(paintable1)
```
results in:
```
Error: type mismatch: got <MediaFile>
but expected one of: 
proc setPaintable(self: Picture; paintable: gdk4.Paintable = nil)
  first type mismatch at position: 1
  required type for self: Picture
  but expression 'media_file1' is of type: MediaFile
```
but `Gtk.MediaFile` implements  `Gdk.Paintable` so i don't understand why i can't use it. I thought gintro would just know what `Gtk.MediaFile` implements, but i guess i'm supposed to be doing something extra?

#latest, quick gtk Video attempt.
```
let media_file1 = gtk4.newMediaFileForFile(gio.newGFileForUri("rtsp://admin:passwd@192.168.1.5:554"))
let video1 = gtk4.newVideo(gtk4.setMediaStream(media_file1))
```

results in:
```
Error: type mismatch: got <MediaFile>
but expected one of: 
proc setMediaStream(self: MediaControls; stream: MediaStream = nil)
  first type mismatch at position: 1
  required type for self: MediaControls
  but expression 'media_file1' is of type: MediaFile
proc setMediaStream(self: Video; stream: MediaStream = nil)
  first type mismatch at position: 1
  required type for self: Video
  but expression 'media_file1' is of type: MediaFile
```
so, `setMediaStream` doesn't accept the `MediaFile` even though `MediaFile` is an implementation of `MediaStream`. Also, i don't really understand the `self: MediaControls` part, especially when the type in the `setMediaStream` gintro source shows the type as `self:Video`. I undertsnad that the Gtk.Video class comes with controls but i'm not clear on how to use the class with gintro in regard to types. I don't want to use controls for this stream, so i'll probably be using the Gtk.Picture method anyways. Just showing both attempts to illustrate my overall misunderstanding about how to use gintro.

Thanks

**Comment by StefanSalewski** [comment]
For GTK4 we have these conversion procs which just do a cast:

```
const GTK4_EPI = """

proc getRootWidget*(self: Widget): Widget =
  let h = self.getRoot
  assert(toBool(g_type_check_instance_is_a(cast[ptr TypeInstance00](h.impl), gtk_widget_get_type())))
  #g_type_check_instance_is_a(cast[ptr TypeInstance00](result.impl), gt)))
  cast[Widget](h)

proc stringObject*(self: gobject.Object): StringObject =
  assert(toBool(g_type_check_instance_is_a(cast[ptr TypeInstance00](self.impl), gtk_string_object_get_type())))
  cast[StringObject](self)

proc fileInfo*(self: gobject.Object): gio.FileInfo =
  assert(toBool(g_type_check_instance_is_a(cast[ptr TypeInstance00](self.impl), g_file_info_get_type())))
  cast[gio.FileInfo](self)
```

>but Gtk.MediaFile implements Gdk.Paintable

So this cast should compile and hopefully work:

```
$ grep -A7 gtk_picture_set_paintable ~/.nimble/pkgs/gintro-#v0.9.2/gintro/gtk4.nim 
proc gtk_picture_set_paintable(self: ptr Picture00; paintable: ptr gdk4.Paintable00) {.
    importc, libprag.}

proc setPaintable*(self: Picture; paintable: gdk4.Paintable = nil) =
  gtk_picture_set_paintable(cast[ptr Picture00](self.impl), if paintable.isNil: nil else: cast[ptr gdk4.Paintable00](paintable.impl))
```

```
  let paintable1 = gtk4.setPaintable(myPicture, cast[gdk4.Paintable](media_file1))
```

If you should get that working, next step would be to create a conversion proc to hide the ugly cast.

Note that your initial call of gtk4.setPaintable(media_file1) seems to make not much sense, as first parameter should be a Picture, and second parameter a Paintable or nil. For second parameter cast[gdk4.Paintable](media_file1) should hopefully work then.

See https://docs.gtk.org/gtk4/method.Picture.set_paintable.html

**Comment by ITwrx** [comment]
i'm using gintro 0.9.4, which appears to have the exact code you pasted above from/in gtk4.nim, so I tried:

```
let media_file1 = gtk4.newMediaFileForFile(gio.newGFileForUri("rtsp://admin:passwd@192.168.1.5:554"))
let myPicture = gtk4.newPicture()
let paintable1 = gtk4.setPaintable(myPicture, cast[gdk4.Paintable](media_file1))
```
which gives me:
`Error: expression 'setPaintable(myPicture, cast[gdk4.Paintable](media_file1))' has no type (or is ambiguous)`
