### ISSUE TITLE
Cant install on arch

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#183]
![image](https://user-images.githubusercontent.com/30507409/137586460-2a0ddf0f-7d69-43a9-9ec3-0a1553565c7f.png)
  
Full log: https://pastebin.com/r3ARC82Z  
  
It just stops on the line `(process:10775): GLib-CRITICAL **: 14:59:28.012: g_once_init_leave: assertion 'result != 0' failed`

**Comment by gavr123456789** [comment]
> Is this a v0.9.5 issue? Can you still install older gintro?  
  
arr, same with all older gintro versions, so it might be GTK, I updated my system recently.  Looks like something with SoupAuth, maybe

**Comment by gavr123456789** [comment]
Now I have 3 GIR files with name Soup in it:  
Soup-2.4.gir, Soup-3.0.gir, SoupGNOME-2.4.gir  
Maybe one of them was added after the update and therefore it gives an error:  
`GLib-GObject-WARNING **: 19:36:40.219: cannot register existing type 'SoupAuth'`

**Comment by StefanSalewski** [comment]
You may have seen this thread in the GTK forum:

https://discourse.gnome.org/t/some-libsoup-3-issue/7807/3

So all that is not easy.

Yesterday I failed installing libsoup 3 from git sources on my Gentoo box, I will try again later.

Maybe you have already some basic Nim and Nimble knowledge, so you may be able to split the gintro install phase into a download and a run phase? In that case you could try to modify the gen.nim script to fix it.

I am doing such experiments not with nimble, but have prepared a special directory on my box, where I manually added some needed files from the oldgtk3 package, which are temporary needed to compile gen.nim. So I modify, compile and run gen.nim in that directory, and copy the generated files to ~/.nimble/pkgs/gintro-#v0.9.5/gintro

That is how I do it for many years now, but maybe at some time in future I will try to learn more about nimble.

Another person does some gintro development recently by temporary forking gintro. Then he modified the gen.nim script in his fork, and tries to install his fork. That way he was able to find a fix for his very old Debian Buster install. We then included that fix in recent version v0.9.5

**Comment by gavr123456789** [comment]
@StefanSalewski Fixed with change versions of WebKit2 JavaScriptCore and WebKit2WebExtension to correct ones.  
Apparently, there are no versions 5.0 of this gir packages: https://valadoc.org/index.htm and also the second screen in my third message.  
Now gintro builds successfully, yay:  
```
...
We continue with the remaining packages...
  Verifying dependencies for gintro@0.9.5
 Installing gintro@0.9.5
   Success: gintro installed successfully.
```

**Comment by gavr123456789** [comment]
> as most people want to use the versions 5.0 of course    
  
As I understand WebKit for GTK 4 is not released yet. The only way to do that is manually build it with `-DUSE_GTK4=ON` flag, only then gir version 5.0 will appears.  
I think we can disable webkit 5 build for gtk 4 until it officially released.
