### ISSUE TITLE
[question/FR?] how to pass two widgets as parameters to callback?

### ISSUE THREAD

**Issue by ITwrx** [StefanSalewski/gintro#185]
The gintro readme has an example of how to pass variables as parameters to callbacks and one of them shows how to pass a widget. That works for me, but trying to pass two widgets gives me a type mismatch error.

 ```
  let home_box = newBox(gtk4.Orientation.horizontal)  
  let home_chooser_btn = newButtonFromIconName("folder-open")
  home_box.append(home_chooser_btn)

  #doesn't work.
  #proc home_chooser_btnCb(b: Button; home_box: Box; home_chooser_btn: Button) =

  #works
  proc home_chooser_btnCb(b: Button; home_box: Box) =
    #can't use b/c i can't pass two widgets yet.
    #home_box.remove(home_chooser_btn)
    let notify_label = newLabel("appended to home_box!")
    home_box.append(notify_label)   

  #  doesn't work
  home_chooser_btn.connect("clicked", home_chooser_btnCb, home_box, home_chooser_btn)

  #works
  home_chooser_btn.connect("clicked", home_chooser_btnCb, home_box)
```
Is there a way to pass two widgets? 

Thanks

**Comment by StefanSalewski** [comment]
>Is there a way to pass two widgets?

The GTK callbacks have exactly one optional parameter. In C we have always to pass NULL if there is no optional parameter, but with Nim and gintro we can just leave it out. To pass more data, we generally create just an object which contains all data in its fields and pass that object. Well actually we pass a ref object. At least I am sure that it works with ref objects, we have used that often. The SDT tool should contain such code, maybe the drawingarea example too. But no reason to look there, it should just work. Often we pass other widgets, which are ref objects too. For plain objects, which live on the stack, the callback macro would have to copy the object into a ref object to extend life time. I am not sure is that may work. Same for tuples, passing tuples as optional arguments should generally work, but I think some years ago someone told us that it did not work, and I told him to just use a ref object. Feel free to investigate the shipped callback macros and improve them. Araq was never very happy with my macros, so you may rewrite them using only functions working on the AST, while I did a lot text manipulations that time, I think it was 2016. I recently added the macros section to the kids book, see http://ssalewski.de/nimprogramming.html#_macros_and_meta_programming. Let us know if there are errors or when we have to improve something.

**Comment by ITwrx** [comment]
Thanks alot, i'll check it out.
