### ISSUE TITLE
I couldn't install gintro

### ISSUE THREAD

**Issue by zaifoo** [StefanSalewski/gintro#196]
I'm working on windows 10.

nimble.exe install gintro

......
C:\msys64\nim\lib\system\nimscript.nim(273, 7) Error: unhandled exception: FAILED: C:\msys64\tmp\gintrosalewski\gen 1

**Comment by StefanSalewski** [comment]
Sorry, I don't use Windows. And when your main target is Windows, I would really not suggest you to use GTK. Nim has 20 other GUI toolkits, some of them should be suited better for Windows.

Of course GTK and gintro can be used for Windows, some people do that.

**Comment by StefanSalewski** [comment]
Well, after consulting line 273 of nimscript.nim I got an idea: The error seems to be related to executing external processes. So it may result from one of the commands in gintro.nimble. From your name I guess that you are from China, may there the command wget be illegal? Or wait, maybe it is exec(td / wd / "gen 1")? But why may that fail? May the exec("nim c gen.nim") have failed before already?

Well, just use fidget :-)

**Comment by zaifoo** [comment]
After install gobject-introspection-runtime in msys2， I can install gintro, and my app compiles and runs fine.

`pacman -S mingw-w64-x86_64-gobject-introspection-runtime`

**Comment by StefanSalewski** [comment]
Fine. I think then we should keep this issue open, as maybe someone other from China has the same problem.

**Comment by codic12** [comment]
It seems the issue is not related to Windows, or China... 
I am in the United States and using Arch Linux and have the same issue

**Comment by nonimportant** [comment]
I've had this problem for a while now and I solved it by [installing GTK for Windows](https://www.gtk.org/docs/installations/windows) via MSYS (and adding C:\msys64\mingw64\bin to PATH), then doing `nimble install gintro` in **administrator mode.** It seems that if not in administrator mode, gen.exe can't find the GTK DLLs and fails. 

This is apparent when running `nimble install gintro --verbose` where it says:
```
Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
69875 lines; 2.149s; 116.746MiB peakmem; proj: xxx\AppData\Local\Temp\gintrosalewski\gen.nim; out: xxx\AppData\Local\Temp\gintrosalewski\gen.exe [SuccessX]
could not load: libglib-2.0-0.dll
```
