### ISSUE TITLE
Code with Gintro fails to compile in Nim devel branch

### ISSUE THREAD

**Issue by xTrayambak** [StefanSalewski/gintro#221]
Hello, so I recently installed gintro and for some reason, the gst code seems to have a syntax error, here is the error generated:
```
/home/<xxxx>/.nimble/pkgs2/gintro-0.9.9-<xxxxxxxx>/gintro/gst.nim(13924, 120) Error: expected ')', but got: '='
```
There is no other error raised, and this is the code:
```nim
import gintro/gst

proc main =
  var pipeline: gst.Element
  var bus: gst.Bus
  var msg: gst.Message
  ##  Initialize GStreamer
  gst.init()
  ##  Build the pipeline
  pipeline = gst.parseLaunch("playbin uri=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm")
  ##  Start playing
  discard gst.setState(pipeline, gst.State.playing)
  ##  Wait until error or EOS
  bus = gst.getBus(pipeline)
  msg = gst.timedPopFiltered(bus, gst.Clock_Time_None, {gst.MessageFlag.error, gst.MessageFlag.eos})
  echo msg.getType
  discard gst.setState(pipeline, gst.State.null) # is this necessary?

main()
```
Is this a bug? Or is gintro just not tested for the development versions of Nim?

**Comment by StefanSalewski** [comment]
>Or is gintro just not tested for the development versions of Nim?

Typically it has always been tested with the latest Nim and GTK versions, once I just installed Arch-Linux on the old notebook of my mom to test some latest GTK, which was not yet available for my Gentoo Linux. But I have not done much Nim in the last 12 months -- when you visit from time to time the Nim forum, you can easily guess the reasons. I will investigate your issue in the next few days, I think I should install the latest GTK for that first.

I hope you did a head install with "nimble install gintro@#head"? And of course, it does not hurt to inspect the line 13924 in gst.nim. Maybe you can just fix it with an editor to make it work immediately?

My general advice for gstreamer is, that it makes not a lot of sense to use it with Nim, as gstreamer is a very low-level library. I recently had a longer discussion with someone, see https://github.com/StefanSalewski/gintro/issues/220

I will tell you when I have fixed this issue, maybe next weekend. Currently, I am still busy fixing a few more bugs in the book, at least I should try to fix the ugly footnote issue and maybe some more bad grammar.

**Comment by StefanSalewski** [comment]
Well, did just a short test with your code, compiles fine here.

nim -v
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-04-28

Will test with latest compiler and lastest gst (Gentoo) soon, but I can not again test with Arch-Linux, as that is always some effort.

**Comment by xTrayambak** [comment]
> > Or is gintro just not tested for the development versions of Nim?
> 
> Typically it has always been tested with the latest Nim and GTK versions, once I just installed Arch-Linux on the old notebook of my mom to test some latest GTK, which was not yet available for my Gentoo Linux. But I have not done much Nim in the last 12 months -- when you visit from time to time the Nim forum, you can easily guess the reasons. I will investigate your issue in the next few days, I think I should install the latest GTK for that first.
> 
> I hope you did a head install with "nimble install gintro@#head"? And of course, it does not hurt to inspect the line 13924 in gst.nim. Maybe you can just fix it with an editor to make it work immediately?
> 
> My general advice for gstreamer is, that it makes not a lot of sense to use it with Nim, as gstreamer is a very low-level library. I recently had a longer discussion with someone, see #220
> 
> I will tell you when I have fixed this issue, maybe next weekend. Currently, I am still busy fixing a few more bugs in the book, at least I should try to fix the ugly footnote issue and maybe some more bad grammar.

Yep, my bad. I was not using the @#head branch. I'll install that and try again.
