### ISSUE TITLE
Type mismatch between GTKSource View and Widget

### ISSUE THREAD

**Issue by HUSKI3** [StefanSalewski/gintro#223]
I'm currently facing an issue with adding a GTKSourceView as a child to a scrolled window.
```nim
# MainView box
    let mainView = newBox(Orientation.vertical, 1)

    # Content
    let paned = newPaned(Orientation.horizontal)

    let editor = newScrolledWindow()

    let editorSourceView = newView()

    editor.setChild(editorSourceView) # Line where the error happens

    paned.setStartChild(
        newLabel("Start")
    )
    paned.setEndChild(
        editor
    )

    paned.position = 400

    # Main content
    mainView.append(paned)
    # Footer
    mainView.append(newLabel("Footer"))
```

With the above, I get the following error:
```bash
Error: type mismatch: got <ScrolledWindow, View>
but expected one of:
proc setChild(self: ScrolledWindow; child: Widget = nil)
  first type mismatch at position: 2
  required type for child: Widget
  but expression 'editorSourceView' is of type: View
18 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: setChild(editor, editorSourceView)
```

Is this an oversight on my side, or did the bindings get messed up during generation?

**Comment by StefanSalewski** [comment]
GTKSourceView is difficult.

Actually, I have not used Nim or Gintro in the lasts months any more -- I tried a few times, but it is difficult to stay motivated for various reasons. Actually, I have the feeling that Gintro has not been used by someone in the last two or three years any more, and there are rumors that it does not work with Nim 2.0. Can you confirm that it basically works still with latest devel compiler, or at least with latest 1.6.14? Because, when investigating your issue, I would have to update my Gentoo box to latest GTK, and then reinstall gintro, and maybe it will then fail completely. My current Nim compiler is a few months old, and it seems at least to work still. But for your concrete issue, it might be better to test with fresh stuff. But maybe you can just use one of the more than 20 other GUI toolkits. Well, more tomorrow, it is late here in Germany.

**Comment by StefanSalewski** [comment]
Before I might investigate your issue: Why do you think you need GtkSourceView? That library is typically used when you intend to create an editor like Gedit. Do you really intend that? I tried 7 years ago with NEd and oldgtk3, and later with NEd2 and gintro. But it is really difficult, and we have to admit: GtkSourceView is very restricted, it is very hard to create a good Nim editor with it. And NimSuggest has its issues, so it is nearly impossible to use it. I ask this, because I supported a few people in the past, with gtkwebview, libnice, gstreamer and more, and they gave then up early.

**Comment by StefanSalewski** [comment]
For me /gintro/examples $ nim r gtk3/sourceview_test.nim

compiles and runs. So I assume you are using GTK4, which is indeed recommended. Or maybe the difference is, that you have a different Nim compiler version. Well, I will test GTK4 soon. I had some trouble finding the latest GtkSource API docs -- actually Google has that trouble. If I remember correctly it is called SourceView5? Or is it GtkSourceView5?

**Comment by StefanSalewski** [comment]
OK, I have converted the GTK4 textview example to SourceView. Works fine for me. Well I have no Nim syntax highlight, but that is missing even for GEdit on my box. It would have to be configured. And I think, for getting syntax highlight at all, one has to load it. You may find an example in my NEd2. If I remember correctly, I got that working, but then I gave up, as all that takes so much time, and on the Gnome forum there is not that much support for GtkSourceView. Here is my modified and working textview example. If that fails for you, it could be the Nim compiler, or maybe your GTK install? I have not yet changed my box, so all is a few months old.

```
import gintro/[gtk4, gobject, glib, gio, gtksource5] # gtksource is not yet available for GTK4

from OS import paramCount, paramStr

proc shutdown(app: Application) =
  echo "shutdown"

proc startup(app: Application) =
  echo "startup"

proc handleLocalOptions(app: Application; vd: VariantDict): int =
  echo "handle-local-options"

proc nameLost(app: Application): bool =
  echo "name-lost"

proc open(app: Application; files: seq[GFile]; hint: string) =
  var
    contents: string
    etagOut: string
    length: uint64
    buffer: TextBuffer
    window: gtk4.Window
    view: gtksource5.View
  echo "open"
  for f in files:
    echo f.uri
  window = app.getActiveWindow
  if window != nil: # instead of opening a new window reuse existing one
    let h = ScrolledWindow(window.getChild)
    view = View(h.getChild)
  else:
    window = newApplicationWindow(app)
    window.title = "Text View"
    window.defaultSize = (800, 600)
    let scrolledWindow = newScrolledWindow()
    view = gtksource5.newView()
    window.setChild(scrolledWindow) # add() for GTK3
    scrolledWindow.setChild(view) # add() for GTK3
  if files.len > 0:
    if loadContents(files[0], cancellable = nil, contents, length, etagOut):
      assert length.int == contents.len
      echo "hint: ", hint
      echo "etag: ", etagOut
      buffer = view.getBuffer
      buffer.setText(contents, contents.len)

  show(window) # showAll() for GTK3

proc commandLine(app: Application; cl: ApplicationCommandLine): int =
  echo "command-line"

proc activate(app: Application) =
  echo "activate"
  let window = newApplicationWindow(app)
  window.title = "Empty Text View"
  window.defaultSize = (800, 600)
  let scrolledWindow = newScrolledWindow()
  let view = gtksource5.newView() # gtksource.newView()
  window.setChild(scrolledWindow) # add() for GTK3
  scrolledWindow.setChild(view)
  show(window) # showAll() for GTK3

proc main =
  let app = newApplication("org.gtk.example", {ApplicationFlag.handlesOpen})#, handlesCommandLine})
  app.connect("startup", startup)
  app.connect("activate", activate)
  app.connect("command-line", commandLine)
  # app.connect("handle_local_options", handleLocalOptions)
  app.connect("open", open)
  app.connect("name-lost", nameLost)
  app.connect("shutdown", shutdown)
  let argLen = paramCount() + 1
  var argStr = newSeq[string](argLen)
  for i in 0 ..< argLen:
    argStr[i] = paramStr(i)
  discard run(app, argLen, argStr) # we have to pass an argString to support open signal handling files

main()
```

```
nim c sourceview.nim 
Hint: used config file '/home/salewski/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/salewski/Nim/config/config.nims' [Conf]
........................................................................................................................................
/tmp/hhh/sourceview.nim(49, 22) Warning: implicit conversion to 'cstring' from a non-const location: contents; this will become a compile time error in the future [CStringConv]
/tmp/hhh/sourceview.nim(14, 6) Hint: 'handleLocalOptions' is declared but not used [XDeclaredButNotUsed]
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
208677 lines; 1.353s; 1.583GiB peakmem; proj: /tmp/hhh/sourceview.nim; out: /tmp/hhh/sourceview [SuccessX]
salewski@hx90 /tmp/hhh $ nim c -f sourceview.nim 
Hint: used config file '/home/salewski/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/salewski/Nim/config/config.nims' [Conf]
........................................................................................................................................
/tmp/hhh/sourceview.nim(49, 22) Warning: implicit conversion to 'cstring' from a non-const location: contents; this will become a compile time error in the future [CStringConv]
/tmp/hhh/sourceview.nim(14, 6) Hint: 'handleLocalOptions' is declared but not used [XDeclaredButNotUsed]
CC: ../../home/salewski/Nim/lib/system/exceptions.nim
CC: ../../home/salewski/Nim/lib/std/private/digitsutils.nim
CC: ../../home/salewski/Nim/lib/std/assertions.nim
CC: ../../home/salewski/Nim/lib/std/formatfloat.nim
CC: ../../home/salewski/Nim/lib/system/dollars.nim
CC: ../../home/salewski/Nim/lib/system.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/glib.nim
CC: ../../home/salewski/Nim/lib/pure/times.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/gobject.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/gio.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/cairo.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/gtk4.nim
CC: ../../home/salewski/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/gtksource5.nim
CC: ../../home/salewski/Nim/lib/std/envvars.nim
CC: ../../home/salewski/Nim/lib/std/cmdline.nim
CC: sourceview.nim
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
208677 lines; 1.587s; 1.583GiB peakmem; proj: /tmp/hhh/sourceview.nim; out: /tmp/hhh/sourceview [SuccessX]
salewski@hx90 /tmp/hhh $ nim -v
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-30
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 7e055413f9bbec81fc9b7e1542695f2886787566
active boot switches: -d:release -d:danger --gc:none

```

**Comment by HUSKI3** [comment]
Thank you for the detailed response. I am indeed trying to build an editor. I've previously built one using Python and GI, but wasn't able to find a good enough solution to package it, in most scenarios flatpak worked but was abysmal due to permission set up required. 

My current nim install is at version:
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10

My original (Python+GI based) editor used GtkSourceView5 and a combination of VTE and some custom components made from GObjects. I was able to port the layout's and buttons, but when I got to the SourceView, the progress stalled. 

I'll try updating to the devel version via choosenim and report my findings. I do understand the difficulties behind sourceview, and it's many (sadly) downgrades from the past versions. Seems like GTK developers love to abandon features. I do have some components that might be weird to carry over, like custom code completion boxes and etc. But as of now, I do not plan on giving GTK up (yet) as it just plain works for most of my use cases.

I'm currently running Bedrock on my development machines, so in theory I could just hotswap the GTK libraries that it's using. I'll try your example and see what it comes up with.

Thank you for your help, I really appreciate it!

**Comment by HUSKI3** [comment]
So I found the following from the devel version. The `nimble install gintro` is borked:
```bash
/tmp/gintrosalewski/gen.nim(1462, 27) Error: type mismatch: got 'seq[string]' for 'split(hhh, {' ', '\t', '\v', '\r', '\n', '\f'}, -1)' but expected 'tuple'
stack trace: (most recent call last)
/tmp/nimblecache-446026292/nimscriptapi_590966540.nim(222, 29)
/tmp/nimble_189516/githubcom_stefansalewskigintro/gintro.nimble(77, 7) installBefore
/tmp/nimble_189516/githubcom_stefansalewskigintro/gintro.nimble(62, 7) prep
/home/link/.choosenim/toolchains/nim-#devel/lib/system/nimscript.nim(265, 7) exec
/home/link/.choosenim/toolchains/nim-#devel/lib/system/nimscript.nim(265, 7) Error: unhandled exception: FAILED: nim c gen.nim [OSError]
       Tip: 5 messages have been suppressed, use --verbose to show them.
nimscriptwrapper.nim(160) execScript

    Error:  Exception raised during nimble script execution
```

Switching back to the 1.6.12, the following happens during install/gen for gtksourceview
`gtksource5..............: Remaining delayed methods: 0 (Fine!)`

...
Oh my god, I am extremely sorry. I only JUST realised what the issue was. I was importing the wrong version of gtksourceview. My original imports looked like the following:
`import gintro/[gtk4, gobject, glib, gio, gtksource] `
instead of the correct:
`import gintro/[gtk4, gobject, glib, gio, gtksource5] `

Sorry for using up your time for such a basic issue. I should've provided my whole file rather than a chunk...

**Comment by HUSKI3** [comment]
@StefanSalewski If possible, I think it'd be really appriciated by future users if you could perhaps add that example to the examples directory so they don't repeat my dumb mistake

**Comment by StefanSalewski** [comment]
>I'll try updating to the devel version via choosenim and report my findings.

Maybe best try my example from above first. I have currently no idea what may be causing the error messages in your initial post.

When you have already experience with GTK, then it may make some sense to continue using it -- I am doing it myself for my PCB CAD project -- well when I am able to find some motivation. I Created that in 2012/2013 in Ruby, created gintro, and ported it to Nim. It would make some sense to continue it with Nim for some time, instead porting again.

For GtkSourceView and your editor: The ugly point is, that we can not really extend GtkSourceView directly in Nim. I think that would be not even possible in Rust, and Rust has the best GTK bindings. So there are always ugly limitations. And GtkSourceView is difficult, it is hard to get support. And for Nim, maybe my biggest issue was the bad NimSuggest behaviour. A lot of crashes, and for larger programs like my CAD tool, it took more than one minute to process the code after a tiny change. They have been talking about IC which would improve Nimsuggest a lot, but they are talking about it since 5 years. I know that IC is hard, Crystal has even more problems.

**Comment by StefanSalewski** [comment]
>Error: type mismatch: got 'seq[string]' for 'split(hhh,

That confirms the rumors. So they removed tuple unpacking silently. Maybe just to block gintro? There are rumors they do not like me and my book. Well, if you should actually intent to use gintro with Nim 2.0, you would be able to fix that, should be not too hard, you would just have to do that unpacking manually, but it is used in multiple places in gen.nim generator script. Should took you a few minutes. I don't think I will do it, it is a good change to just stop with it. And I have still an old local version, with which I can play if I want.

 >I was importing the wrong version

That was one of my guesses, but I still do not understand the error messages of the compiler. But it is clear that it will not work with the wrong version.
