### ISSUE TITLE
Need advice with Plotting

### ISSUE THREAD

**Issue by r3d9u11** [StefanSalewski/gintro#25]
Hi. I need advice: I'm looking for gui-libs to write a gui application with data visualization. I'm found a two actual libraries/widgets: [gtkDatabox](http://www.eudoxos.net/gtk/gtkdatabox/) and [gtkmm-plplot](https://tschoonj.github.io/gtkmm-plplot/installation_instructions.html). Is it possible to use Gtk3 + Glade + <one of these libraries> + Nim/gintro, what can be necessary for this?

Or maybe somebody knows a better widgets/libs/solution?

Thanks.

**Comment by StefanSalewski** [comment]
As far as I can remember there has been never much support for plotting in GTK.  Data visualization is a wide area, and defining useful APIs is difficult.

gtkDatabox seems to be very old, and seems to support only old GTK2.  gtkmm-plplot seems to be more recent, but it is C++ which may make using it from Nim more difficult.

Generally GTK plotting is done with cairo graphics library, drawing in a GtkDrawingArea Widget. So one can create advanced plotting tools with it. gintro package contains a very basic example drawing a plain sine curve. When using cairo one has to regard that cairo currently has no good GPU support, so drawing is not very fast. I used cairo for this tool: http://ssalewski.de/PetEd.html.en so it is fast enough for such stuff, but may be not for advanced animations.

Another solution may be using gnuplot, I think there exists Nim bindings for that tool.

**Comment by r3d9u11** [comment]
@StefanSalewski thanks for detailed answer!
