### ISSUE TITLE
Error: unhandled exception: VM is not built with 'gorge' support [ERecoverableError]

### ISSUE THREAD

**Issue by barcharcraz** [StefanSalewski/gintro#28]
I get this error when installing via nimble.

**Comment by StefanSalewski** [comment]
Do you use latest devel Nim  compiler version? Maybe even Windows or Mac?

Gintro was working well with stable Nim 0.18, at least for Linux 64 bit. And I think it is still working for this configuration.

For Nim 0.19 (1.0 release canditate ?) there is some work to do, that is not surprising, as Nim 0.19 has some breaking changes.

But as long as there are no serious Gintro users, or at least people who intent to use it seriously, I think I will delay that changes. As it makes not too much sense fixing things which no on uses.

We have some other GUI libs for Nim, like NimX, IUP, libui, QML. Maybe not that powerfull as GTK, but also interesting and maybe easier to use for people without GTK experience.

**Comment by barcharcraz** [comment]
yes I'm on devel.

**Comment by StefanSalewski** [comment]
Have just shipped gintro 0.4.4 which works fine for my latest Nim devel 18.1

Hope it will still work for stable Nim 0.18

**Comment by StefanSalewski** [comment]
Closing -- you may reopen when necessary.
