### ISSUE TITLE
ambiguous identifier: 'PtrArray'

### ISSUE THREAD

**Issue by aeldemery** [StefanSalewski/gintro#39]
Compiling the latest release produce the following error:
gintro-0.4.8/gintro/gtk.nim(40701, 102) Error: ambiguous identifier: 'PtrArray' --use atk.PtrArray or glib.PtrArray
Solution for me:
changing all occurrences with glib.PtrArray solved for me although I'm not sure if this is right!

**Comment by StefanSalewski** [comment]
Thanks for reporting.
In the current gtk.nim on my Linux box PtrArray was not used, so I missed that error. Indeed the PtrArray from glib.nim is the right one, the dummy in atk.nim was wrong. I removed that.

Will close this issue, please reopen if problems persist.
