### ISSUE TITLE
Wrong interface for modifyBg (and modifyFg)

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#4]
The interface to bg_modify is defined this way:

proc gtk_widget_modify_bg*(self: ptr Widget00; state: StateType; color: gdk.Color) {.
    importc: "gtk_widget_modify_bg", libprag.}

proc modifyBg*(self: Widget; state: StateType; color: gdk.Color) =
  gtk_widget_modify_bg(cast[ptr Widget00](self.impl), state, color)

As "gtk_widget_modify_bg" expects a pointer to color, it  should be:

proc gtk_widget_modify_bg*(self: ptr Widget00; state: StateType; color: var gdk.Color) {.
    importc: "gtk_widget_modify_bg", libprag.}

proc modifyBg*(self: Widget; state: StateType; color: var gdk.Color) =
  gtk_widget_modify_bg(cast[ptr Widget00](self.impl), state, color)

**Comment by StefanSalewski** [comment]
Thanks for testing.

I think gtk_widget_modify_bg() is deprecated -- I gave a CSS example for color setting in the tutorial.

Of course when it is a bug, I fill fix it. I am not sure if it is really a bug, as some object types are defined with byCopy pragma, so objects are passed to C lib as value types in API but compiler pass the pointer. I will try to investigate that soon...

**Comment by lscrd** [comment]
Thanks for your quick answer. I am trying to convert a program written in Nim using Gtk2 to Gtk3, so I use, at least for now, the legacy interface as there are a lot of deprecated things in Gtk3 (HBox and VBox, for instance). By the way, I really appreciate the cleaner interface of "gintro", but the conversion is not so easy.

Presently, "modifyBg" crashes and adding "var" makes it work, but I agree this may not be the best way to solve the problem.

**Comment by StefanSalewski** [comment]
> convert a program written in Nim using Gtk2 to Gtk3

You may try to use oldGtk3 nimble package or the single GTK3 files from github.com/ngtk3 as an intermediate step if your program is large. OldGtk3 package is low level, but should have very few bugs as it is generated by c2nim. Gintro package has bugs still, I am sure. So converting a large GTK2 program like Aporia or NEd is difficult currently. But for small programs like my chess board it should work already.

Currently I have to fix memory management of GTK boxed types, their memory is not freed in actual  version. If that is done I will investigate your issues.

**Comment by StefanSalewski** [comment]
Ah yes, I think you are absolutely right. When I now think about it -- it may have been a wrong wiring in my brain. I think I have marked some objects with byCopy pragma, but what I intended is the opposite .. byRef. ByRef is the default already, and byCopy is definitely wrong for GTK. You may test yourself -- search for byCopy string and replace with byRef. In single modules, or in tests/gen.nim. After replacing in gen.nim you have to do nimble prepare and nimble install again to generate all modules new. Have to leave for now -- bye...

**Comment by lscrd** [comment]
I have changed in tests/gen.nim as you have described and, indeed, it works. It’s better that my work around and may have fix other interfaces too. Thanks !

**Comment by StefanSalewski** [comment]
Fixed. Note that modifyBg/modifyFg is deprecated and may not work properly for all widgets any more, as widgets may have gradients and such. Better use CSS, tutorial contains an example.

But this example seems to have an effect still:

```nim
# nim c button.nim
import gintro/[gtk, glib, gio, gobject, gdk]

proc buttonClicked (button: Button) =
  button.label = utf8Strreverse(button.label, -1)
  const c = (gdk.Color)(pixel: 0, red: 60000, green: 0, blue: 0) # makes window title red
  modifyFg(button.parent, StateType.normal, c) # deprected, may not work properly

proc activate (app: Application) =
  let window = newApplicationWindow(app)
  window.title = "GNOME Button" # will be red after button is clicked.
  window.defaultSize = (250, 50)
  let button = newButton("Click Me")
  window.add(button)
  button.connect("clicked",  buttonClicked)
  window.showAll

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", activate)
  discard app.run

main()
```

Closing, please reopen if problems occur.
