### ISSUE TITLE
How to use GtkSourceView

### ISSUE THREAD

**Issue by curioussavage** [StefanSalewski/gintro#40]
For context I am a beginner to both nim/c and gtk.

I tried to use a glade template to but it won't compile since it uses GtkSourceView. What would be involved in making that widget usable with this library/nim?

**Comment by StefanSalewski** [comment]
> I am a beginner to both nim/c and gtk.

That is a very bad combination. Learning C, GTK and Nim, each at a time is not too difficult, but all three at the same time is hard. I generally recommend using gintro/GTK only for people already familiar with GTK. GTK is not very popular today, so it may make not much sense learning it. And when you really want to learn GTK yet, is is very helpful to know C already, because most examples are in C. And there are really not many examples available at all, often we refer to the old GTK2 book of A. Krause from 2006 for example. GtkSourceView is already an advanced topic, I used it in the NEd Nim editor, but that editor still uses oldGTK3 Nim bindings. If you have a working C example for what you intent to do with GtkSourceView (other language is ok as well when code is working, for example Python) then I can help you converting it to Nim. Generally it is easy. But I have currently not the time to teach you all the basics -- recently someone asked how to do a multi-column treeview, so I gave an example in Nim forum, and then the one who asked disappeared. I do understand why he disappeared, and it is OK, but my time is limited currently. (See https://forum.nim-lang.org/t/4711 )

Using Glade/GtkBuilder is another topic, I was already asked about that, I think there is a minimal example in one of the gintro issues. The problem of glade is, that it generally returns a plain untyped pointer. But in Nim we generally use typed objects, to get type test at compile time, and not undefined behaviour at runtime when there is an error. So some patches to gintro are needed, and a lot of testing. Generally I do not like Glade that much, for high level languages I see not much advantage in using it. I used it for NEd editor, but that was mainly just for testing.

There are other GUI toolkits available for Nim, maybe you can use one of them.

**Comment by StefanSalewski** [comment]
Of course you can generate a GtkSourceView widget without glade as every other widget like

```nim
import gintro/[gtk, glib, gobject, gio, gtksource]

proc appActivate (app: Application) =
  let window = newApplicationWindow(app)
  window.title = "GTKSourceView"
  window.defaultSize = (250, 350)
  let view = newView()
  window.add(view)
  window.showAll

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard app.run

main()
```

You can type in some text and do some basic ops like select and copy. But all the other stuff is some work. Do you want to write an editor? NEd is an example of a very simple one: https://github.com/StefanSalewski/NEd

**Comment by curioussavage** [comment]
Thanks for responding! I can at least read c code and more often than not make sense of it. And I have written several simple Gtk apps. Read Doms book but I forgot a lot since I don't have a ton of time to code for fun these days. I think what I was really trying to ask was how to use the gobject introspection data from another gtk based lib to use the widgets provided by it with this lib. I had assumed that since GtkSourceView is shipped in a separate package (in Ubuntu at least) that it wasn't included in this lib. But I would still like to have an idea of how to do this and I'm assuming that the code to do that is in the old gtk repo since this one looks pretty bare. I would really like to use [libhandy](https://gitlab.gnome.org/Community/Purism/libhandy) so I will need to figure that out.

I tried adding the import above but it still didn't work.`Error: unhandled exception: builder.ui:46:1 Invalid object type 'GtkSourceView' [GException]` I'm assuming it couldn't find the shared lib for source view on my system? I have `libgtksourceview-3.0-1` installed along with the dev and common debs. Is it the version?

**Comment by StefanSalewski** [comment]
OK, so you have at least some experience in GTK, and you seems to be not focussed at Windows, so Nim with GTK makes some sense for you.

Are you able to compile and run my above example code? If not, then your GtkSourceView lib may be not correctly installed. I think Windows users generally are missing GtkSourceView, and for Linux users GtkSourceView may be a separate package, and maybe it is necessary to install a devel package, as some distros separate binary and devel. If it does really not work, you may try to find a C code example that uses GtkSourceView and try to compile and run that.

I am confused by your error message, are you trying to use GtkSourceView with builder? Well maybe that is the problem? Or are you trying to use  libhandy with Nim? That will not work for sure, as it is not included in current gintro. In case  libhandy supports gobject-introspection, it may be easy to add it to gintro. If we have luck, it is only adding a single line to gen.nim file, but it can be some more work. I have the impression that  libhandy is for mobile devices, so note that GTK/GNOME support for mobile is considered very bad, most people prefer Qt for mobile. But Qt is not available for Nim currently, only QML was.

**Comment by StefanSalewski** [comment]
Well, I did a short google search about that libhandy. Seems to be a very exotic and new lib, I can not find something about introspection support, and it is not available as a package for Gentoo-Linux. So I guess you will have a really hard time with libhandy.

**Comment by curioussavage** [comment]
I'm not worried about libhandy for now. I can look into that myself later on I guess. It does support gobject introspection though, people are using it with the python gobject bindings. It's not going to be exotic for long. Many of the new core gnome apps are starting to use it in 3.32 I think. Purism is working closely with the gnome and gtk devs to get gnome mobile going. Some the lib might even end up in gtk4 too.

I do have a `GtkSourceView` widget in my glade template. Darn I just tried compiling your example and it works so seems like either there is some more setup required for builder to deal with it or there is something else wrong.

**Comment by StefanSalewski** [comment]
Fine that my example is working for you. Using glade/builder can be more difficult, I had some problems with glade itself when doing NEd. I think I found no nice glade tutorial, only a very old one. And I asked on gtk mailing list, without getting really helpful advice.

You may have noticed that recently a GTK discourse forum was started, see

https://discourse.gnome.org/

maybe that will increase GTK popularity a bit again.

Maybe you can find a small C example which uses GtkSourceView with builder, than it should be not hard to convert it to Nim. Making example code from scratch or extracting from a large app is some work unfortunately. For libhandy, I would have to figure out how to install it parallel to my gentoo package manager and how to access its introspection data.

**Comment by curioussavage** [comment]
Great Idea about discourse. I'll post there and see if anyone can give me some direction about the widget with glade. 

There are a bunch of developers looking at options for making gtk apps for the upcoming linux phones and I think Nim is a nice choice. Outside core gnome people I don't think many want to use C. Vala is really nice but has a tiny community. Python is easy but isn't the best choice for apps running on such a battery and resource constrained device. Anyways that's all kind of a tangent so I'll stop now.

**Comment by curioussavage** [comment]
Looks like somebody already responded https://discourse.gnome.org/t/using-gtksourceview-in-glade-template/652

**Comment by StefanSalewski** [comment]
OK, I hacked together a working example with builder and GtkSourceView. One of the tricks is that we have to register the GtkSourceView widget first, see

 https://stackoverflow.com/questions/10524196/load-gui-from-a-glade-with-gtksourceview-in-pygobject

Another post found with google said that instead of register we can create a dummy sourceView first, I did that because I have not yet found the C function for register, python name is not that clear for me. Here is the code, it is ugly of course due to the cast, but I hope it is a starting point for you.

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.18.3 -->
<interface>
  <requires lib="gtk+" version="3.12"/>
  <object class="GtkApplicationWindow" id="window">
    <property name="visible">True</property>
    <property name="can_focus">False</property>
      <child>
      <object class="GtkScrolledWindow" id="left_scrolledwindow">
        <property name="visible">True</property>
        <property name="can_focus">True</property>
        <property name="shadow_type">in</property>
        <child>
          <object class="GtkSourceView" id="gtksourceview">
            <property name="visible">True</property>
            <property name="can_focus">True</property>
            <property name="has_tooltip">True</property>
            <property name="left_margin">2</property>
            <property name="right_margin">2</property>
            <property name="tab_width">4</property>
            <property name="auto_indent">True</property>
            <property name="indent_on_tab">False</property>
          </object>
        </child>
      </object>
      </child>
  </object>
</interface>
```

```nim
import gintro/[gtk, glib, gobject, gio, gtksource]

proc appActivate(app: Application) =
  var
    builder: Builder
    value: Value
    button: Button
  
  var dummy = newView()
  builder = newBuilder()
  discard addFromFile(builder, "builder.ui")
  let window = cast[ApplicationWindow](getObject(builder, "window"))

  #discard value.init(typeFromName("GObject"))
  #value.setObject(app)
  #setProperty(window, "application", value)

  window.setApplication(app) # above 3 lines work, but just calling this function is simpler

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard run(app)

main()

```

**Comment by curioussavage** [comment]
Wow, I really didn't expect this much help but thanks! It works!

**Comment by curioussavage** [comment]
It looks like this is the function you have to call https://developer.gnome.org/gobject/stable/gobject-Type-Information.html#g-type-ensure I don't think the library exposes what I need though since that method accepts a GType the generated nim lib does not export anything of that type.

**Comment by StefanSalewski** [comment]
You can get GTypes from names using typeFromName() -- that function is used in the gintro listview example. One problem is that you must know the correct type name before.

I just did a short test with g_type_ensure() but it does not really work.

Looking at NEd sources I saw that there discard viewGetType() is called, which is a call to gtk_source_view_get_type(). But that is not provided by gobject-introspection.

So please use the dummy widget approach for now. We have to investigate these issues later.

Reference for the GType name guessing:

https://mail.gnome.org/archives/gtk-list/2017-September/msg00137.html

**Comment by StefanSalewski** [comment]
```
// gcc -o t t.c `pkg-config --libs --cflags gtk+-3.0`
#include <gtk/gtk.h>
#include <stdio.h>
int main(int argc, char *argv[]) {

  printf("%s\n", g_type_name(G_TYPE_STRING));
  printf("%s\n", g_type_name(G_TYPE_SOURCE));

  return 0;
}

// Well, really hard to guess, output is
// gchararray
// GSource
```

**Comment by StefanSalewski** [comment]
Fix is available in latest release:

```nim
import gintro/[gtk, glib, gobject, gio, gtksource]

proc appActivate(app: Application) =
  var builder = newBuilder()
  discard addFromFile(builder, "builder.ui")
  let window = getApplicationWindow(builder, "window")
  window.setApplication(app)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard run(app)
main()
```

For GtkSourceView we have now getType() functions. Calling these seems to register the types. For SourceView it it done automatically, so above works out of the box.

And we have get() functions to fetch objects from builder. I have added these manually -- let me know when there are still missing some.

And new drawingArea.nim example is included.

**Comment by curioussavage** [comment]
Really cool! I will give it a try asap.

**Comment by StefanSalewski** [comment]
As builder/glade example and getType() functions are provided now, I will close this issue.

https://github.com/StefanSalewski/gintro#gtk-builderuser-interfaces-created-with-the-glade-tool

Note that gtksourceview is currently not available for GTK4 from upstream.

**Comment by japajoe** [comment]
Just ran into this myself with my C# bindings, and doing g_ensure_type does the trick. Important to note is that you have to do this before creating a builder object, otherwise it won't work. There is no need to create a dummy object (which I tried and didn't work anyway).
