### ISSUE TITLE
Signal connect error

### ISSUE THREAD

**Issue by zestyr** [StefanSalewski/gintro#42]
I get this error when trying to connect to the "size-allocate" signal: 
```nim
test.nim(6, 4) template/generic instantiation of `connect` from here
gintro-0.4.16/gintro/gimpl.nim(4, 5) Error: cannot generate VM code for ct4nt = ["int32|int", "uint32|int", "gboolean|toBool", "cstring|$$"]
```

Below is a minimal example to reproduce it:
```nim
import pkg/gintro/[gobject, gtk, gdk]

proc test(box: Box; allocation: Rectangle) = discard

let box = newBox(Orientation.vertical, 0)
box.connect("size-allocate", test)
```

I did some troubleshooting and it only affects some signals but not all. Some of the affected are "size-allocate", "show-help", "state-changed", but signals like "realize", "draw" and "activate"  don't produce this error. Modifying `ct4nt` to eg. `["int"]` doesn't fix the error. Only tested with latest gintro and Nim devel.

**Comment by StefanSalewski** [comment]
Thanks for reporting.

Problem seems to be that signals like

https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-size-allocate

uses an additional parameter, gdk.Rectangle in this case. I think the  initial release of gintro was tested for signals with additional parameters, but maybe some parameter types are special, maybe distinction in/out parameters. Or it may have been broken by never compiler versions, maybe I have missed including tests for that, can not really remember currently.

I will investigate that. Unfortunately I just spent whole last weekend creating version 0.4.16 released yesterday, which includes another cairo drawing example and better support for GtkSourceView and Gtk-Builder, as requested by a user. So it may take some time before I can continue working again on gintro -:) And the issue may be not trivial, it is related to the signal-connect macros. I will try to investigate it in the next days.

**Comment by StefanSalewski** [comment]
Ah yes, problem is obvious.

Included test case was cairo_anim.nim using draw signal. But difference to size-alloc is, that draw signal is related to cairo context, which is ptr/ref. But size-alloc is related to gdk.Rectangle which is value type (Object). So fix for the macros is needed.

Are you serious using GTK? If yes, how fast do you need a fix?

**Comment by zestyr** [comment]
Thank you for the quick reply. I'm using it for a long-term hobby project so I don't mind waiting.

**Comment by StefanSalewski** [comment]
Finally it seems to be only a compiler change, which the error message told us correctly.

For use in macros we have to use const arrays now, let ct4nt is invalid.

This example works fine for me now:

```nim
# https://lists.cairographics.org/archives/cairo/2016-October/027791.html
# Nim version of that plain cairo animation example

import gintro/[gtk, gdk, glib, gobject, gio, cairo]
import math

const
  NumPoints = 1000
  Period = 100.0

proc invalidateCb(w: Widget): bool =
  queueDraw(w)
  return SOURCE_CONTINUE

proc sineToPoint(x, width, height: int): float =
  math.sin(x.float * math.TAU / Period) * height.float * 0.5 + height.float * 0.5

proc sizeAllocateCb(widget: DrawingArea; rect: gdk.Rectangle) =
  echo "sizeAllocateCb ", rect.x, " ", rect.y, " ", rect.width, " ", rect.height 

proc drawingAreaDrawCb(widget: DrawingArea; context: Context): bool =
  var redrawNumber {.global.} : int
  let width = getAllocatedWidth(widget)
  let height = getAllocatedHeight(widget)
  for i in 1 ..< NumPoints:
    context.lineTo(i.float , sineToPoint(i + redrawNumber, width, height))
  context.stroke
  inc(redrawNumber)
  return true # TRUE to stop other handlers from being invoked for the event. FALSE to propagate the event further.

proc appActivate(app: Application) =
  let window = newApplicationWindow(app)
  window.title = "Drawing example"
  window.defaultSize = (400, 400)
  let drawingArea = newDrawingArea()
  window.add(drawingArea)
  showAll(window)
  discard timeoutAdd(1000 div 60, invalidateCb, drawingArea)
  connect(drawingArea, "draw", drawingAreaDrawCb)
  connect(drawingArea, "size-allocate", sizeAllocateCb)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", appActivate)
  discard run(app)

main()
```

Unfortunately error messages for connecting signals are not that helpful, but at least correctness is tested. Will close this issue, please reopen when necessary.

**Comment by zestyr** [comment]
Indeed it works now, thank you very much for the quick fix.
