### ISSUE TITLE
gen.nim(118, 19) Error: undeclared identifier: 'initHashSet'

### ISSUE THREAD

**Issue by royneary** [StefanSalewski/gintro#43]
Since 6a49f964f57686f1dc45c01b9c2703950a3117c5 I can't compile anymore using the stable Nim compiler 0.19.4.

I think you did that because ``proc initSet`` [has been renamed](https://github.com/nim-lang/Nim/issues/10730) to ``proc initHashSet``, but it's not in stable Nim yet. In my opinion gintro should not depend on an unstable compiler.

**Comment by StefanSalewski** [comment]
Oh, big mistake!

What do I have to do? Rename it back and release new version? Makes that sense?

Maybe people still using compiler 0.19.4 can install gintro 0.4.11, that one still has the old names. And should work fine, latest fix was mainly for a single user wanting builder and sourceview support. (You may be wondering about release numbers -- well I had some problems to get nimble install working, so I had to push tags multiple times yesterday.)

**Comment by royneary** [comment]
Yes, renaming ``initHashSet`` to ``initSet`` in ``gen.nim`` should fix the issue. I think packagers are very happy with frequent bug-fixing releases :-)

**Comment by StefanSalewski** [comment]
Fixed in latest release 0.4.17

Have renamed initHashSet() back to initSet().

Can not test with older compiler version, but I hope it will work for you.
Will close issue, please reopen when there are more problems with older compilers.
