### ISSUE TITLE
Using enum for masks

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#5]
Event masks, for instance, are defined using  enum values. Unfortunately, in procs such as "addEvents", the mask is an int. So, we have to write things like this:

```Nim
  w.addEvents(ord(EventMask.enterNotifyMask) or
              ord(EventMask.leaveNotifyMask) or
              ord(EventMask.buttonPressMask))
```
This is a bit cumbersome. I think that enums are better than integer constants, but maybe we could use a set of EventMask rather than an int. I don’t know if this can be easily done, though.

**Comment by StefanSalewski** [comment]
Fixed. Use code like

```nim
  darea.addEvents({EventFlag.buttonPress, EventFlag.enterNotify})
```
Closing, please reopen when necessary.
