### ISSUE TITLE
Got cairoimpl.nim(646, 22) Error: undeclared identifier: 'Rectangle' when compile sample

### ISSUE THREAD

**Issue by cndkhuong** [StefanSalewski/gintro#60]
.nimble/pkgs/gintro-0.6.1/gintro/cairoimpl.nim(646, 22) Error: undeclared identifier: 'Rectangle'

**Comment by StefanSalewski** [comment]
Seems you are from China, can you access Nim forum?

Because it seems that your error is

https://forum.nim-lang.org/t/5420#33920

Basically you use an too old GTK, the issue is with 3.22 while 3.24 is fine.

If you can not read forum I will post some more details here soon...

**Comment by StefanSalewski** [comment]
Or maybe you can access

https://github.com/StefanSalewski/gintro/blob/master/README.adoc

There we tell

"Starting with current version v.0.6.0 we support gstreamer (gst). At the same time we have split cairo module into an gobject-introspection basic part and an manually created part. Unfortunately the gobject-introspection is not available for very old GTK/cairo libraries, so installation may fail for you. Use v0.5.5 in this case. Also we support gBoxed types now, this is assumed to work well but is not well tested yet. Command to install older releases should be something like nimble uninstall gintro followed by nimble install gintro@v0.5.5"

In the free world nearly every serious user should have GTK 3.24 already. In China that may be different. If there are many people with serious desire using GTK3 with Nim then we would have to provide a fix. Maybe simplest fix for you is to remove "include cairoimpl" statement in

```
$ grep include ~/.nimble/pkgs/gintro-0.6.1/gintro/cairo.nim 
include cairoimpl
```

That will restrict you when you want to use cairo drawing, but other GTK should work. Or just use old version 0.5.5.

**Comment by cndkhuong** [comment]
Hi, thanks for reply, I can see problem now by old gtk version. And I'm not Chinese, I'm Vietnamese , I'm free what's problem with my country ? I'm using ElementaryOS with GTK 3.22 as below
$dpkg-query -W libgtk-3-bin
libgtk-3-bin	3.22.30-1ubuntu4

**Comment by StefanSalewski** [comment]
Great that you live in a free country. I hope that you can get a never version of GTK then. For testing gintro 0.5.5 is not that bad, it should  work with GTK 3.22. Maybe you will not like GTK so much at all...
