### ISSUE TITLE
How to access object in Box object

### ISSUE THREAD

**Issue by dmknght** [StefanSalewski/gintro#67]
Hi! I am having code like this. I tried google search and i found nothing useful so idk if gtk doesn't support it or gintro doesn't support.
```
proc boxOption1():  Box =
  let getText = newEntry()
  <draw something in here>

proc boxOption2():  Box =
  let getText = newEntry()
  <draw something in here>

proc refresh() =
  <main widget code>
  selectBox = newComboBoxText()
   selectBox.appendText("Option1")
  selectBox.appendText("Option2")
  if selectBox.active ==  0:
    mainWidget.add(boxOption1)
  else:
    mainWidget.add(boxOption2)

proc main() =
   add_timeout(refresh)
```
I  want to access `getText` in `boxOption()`  to get latest input values. it tried global object but i got `nil` error. So i am wondering if i can access value like `boxOption1.getElement(getText)`? By now i'm having 2 options:
1. Draw 2 `boxOptions` in each if else condition. I don't use `proc`. But it will be bad for the code.
2. Use argument to pass entry text but it is a little bad because i can have so many arguments. P/s: I think i had `nil` error too.  P/s2: it doesn't have `nil` error but it is a little bad for code syntax i think and the `refresh` for the widget doesn't work. It doesn't get latest value after i change it.

**Comment by dmknght** [comment]
I am  able to do it by add native boxes and use hide / showall method. The args is a must do thing. It looks bad but it is a must do. I think i can optimize it.

**Comment by StefanSalewski** [comment]
I am currently not really able to understand your problem.

Do you know that GTK is not a Immediate mode GUI, but a retained mode one?

See https://en.wikipedia.org/wiki/Immediate_mode_GUI

Generally in GTK apps there is no add_timeout() and no <draw something in here> in ordinary widget code. Exception may be animations where you draw for example to a drawing area.

It would be very helpful if you could provide an example in another language, preferable C, Python or Java-Script.

Also note that we have nearly a dozen GUI toolkits for Nim now, some are Immediate mode ones, maybe they are better for your task.

**Comment by dmknght** [comment]
> I am currently not really able to understand your problem.
> 
> Do you know that GTK is not a Immediate mode GUI, but a retained mode one?
> 
> See https://en.wikipedia.org/wiki/Immediate_mode_GUI
> 
> Generally in GTK apps there is no add_timeout() and no in ordinary widget code. Exception may be animations where you draw for example to a drawing area.
> 
> It would be very helpful if you could provide an example in another language, preferable C, Python or Java-Script.
> 
> Also note that we have nearly a dozen GUI toolkits for Nim now, some are Immediate mode ones, maybe they are better for your task.

Hi! Thank you for your answer. I'm  doing the gui like this:
![Screenshot at 2020-03-29 19-06-10](https://user-images.githubusercontent.com/29118926/77881458-90c3fb80-724e-11ea-9365-c77f0b7e9473.png)
![Screenshot at 2020-03-29 19-06-13](https://user-images.githubusercontent.com/29118926/77881461-91f52880-724e-11ea-80f9-7a48ae7dffd4.png)
As you see, when i select different option in combobox i can get different layout. So i was unable to get values from the new section i added. I'm having a solution for it and i am doing it.
