### ISSUE TITLE
GType size

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#7]
In the gtk2 interface, "GType" is defined as "gulong" i.e. "clong" (64 bits). In "gintro", it is defined as "cint" (32 bits). Looking at "gtype.h" in the system header files, it is a "gulong" (or a "gsize" which is equivalent).

I have quickly wrapped a function still missing in "gintro" as I need it, and it crashes with the 32 bits GType. Changing locally GType to a 64 bits "gulong", it doesn’t crash (not sure that my quick and dirty wrapping works however).

I’m pretty sure the right size for GType is 64 bits. Could you check, please ?

**Comment by StefanSalewski** [comment]
Yes, you are right. GType was not provided by gobject-introspection, so I inserted it manually and did it wrong.

From c headers we have

```
$ grep -A5 GLIB_SIZEOF_S *.h
gtype.h:#if     GLIB_SIZEOF_SIZE_T != GLIB_SIZEOF_LONG || !defined __cplusplus
gtype.h-typedef gsize                           GType;
gtype.h-#else   /* for historic reasons, C++ links against gulong GTypes */
gtype.h-typedef gulong                          GType;
gtype.h-#endif

```
gsize is Nim's csize, which is generally 8 byte. So I think I will define "const GType = distinct csize".

**Comment by StefanSalewski** [comment]
Should be fixed. I have copied the code from oldGtk3 package:

```
diff /home/stefan/gitest/tests/nim_gi/glib.nim /home/stefan/.nimble/pkgs/gintro-0.2.0/gintro/glib.nim
42a43,48
> const
>   GLIB_SIZEOF_VOID_P = sizeof(pointer)
> const
>   GLIB_SIZEOF_SIZE_T* = GLIB_SIZEOF_VOID_P
> const
>   GLIB_SIZEOF_LONG* = sizeof(clong)
44c50,58
<   GType* = distinct cint
---
>   Gssize* = csize
> type
>   Gsize* = csize # note: csize is signed in Nim!
> when GLIB_SIZEOF_SIZE_T != GLIB_SIZEOF_LONG or not defined(cpp):
>   type
>     GType* = Gsize
> else:
>   type
>     GType* = culong
```

```
import gintro/glib
echo sizeof(GType)
```

```
$ nim c -r t.nim 
8
```
