### ISSUE TITLE
Create a kaspersky-like window

### ISSUE THREAD

**Issue by dmknght** [StefanSalewski/gintro#70]
Hi! I'm trying to create something like interface like kaspersky (image above) but i don't know how. I don't even know which object should i use for this. Please forgive me if i'm doing wrong. I really don't have any resource for this.
1. The top area is current status of the program (or something i can check later). It shows: running / stopped and when i click on it i can open new widget or change main windows to its layout
2. The area bellow has 3 or 4 boxes (or buttons). When i select on 1 in these objects, i can change main widget to its layout (i don't know how to explain this well. For example in Kaspersky, if you click on scan button the main widget goes to scan widget). Select "back" button goes back to main widget.
![Screenshot at 2020-05-05 05-22-05](https://user-images.githubusercontent.com/29118926/81025858-a210b100-8e67-11ea-89dd-bf16c7547f43.png)

**Comment by StefanSalewski** [comment]
These type of questions you really should ask on the GTK forum as it is not really related to the Nim bindings.

https://discourse.gnome.org/

I can currently not invest this question, as I have to adjust gintro to latest GTK 3.98.3, see

https://discourse.gnome.org/t/recent-gtk-3-98-nim-example-fails-to-compile/3262/9

**Comment by dmknght** [comment]
Thank you. Sorry for my offtopic question :'(. Close because of this reason.
