### ISSUE TITLE
running example code gives me "cannot open file: gintro/gtk "

### ISSUE THREAD

**Issue by geohuz** [StefanSalewski/gintro#72]
Using catalina 10.15.4, nimble installed gintro without any problem, but running the app0.nim source code give the error :" cannot open file: gintro/gtk"

**Comment by StefanSalewski** [comment]
From your github page I assume you are located at China?

Unfortunately I have absolutely no idea for your error report.

Are you able to access the Nim forum of the free world? If yes, then you may ask there, there we have some smart people, some from China.

If you can not access hat forum, then there is  https://nim-lang-cn.org/
I can not read that, maybe you can, and maybe ask there?

Or maybe you can access Nim IRC and ask there, some Chinese people can access IRC.

OK, I will forward you issue to IRC for you.

**Comment by PMunch** [comment]
It seems like the nimble directory is not in the path nim uses when compiling. You could try to pass it manually.

**Comment by StefanSalewski** [comment]
PMunch, in that case I assume that all nimble installed packages should fail? But I guess for geohuz only gintro has that problem?

geohuz, to verify that gintro is installed successfully you should search for a directory which contains textual files like gtk.nim, gobject.nim and many more. For linux that would be  ~/.nimble/pkgs/gintro-0.7.3/gintro but for your catalina OS that path may be different.

**Comment by unihernandez22** [comment]
Solution: Don't use `sudo` for install.

`nimble install gintro`

**Comment by StefanSalewski** [comment]
I think we can close this now.
