### ISSUE TITLE
Got “undeclared identifier: 'Status'” in “cairoimpl.nim”

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#86]
I imported "cairo" and "cairoimpl". When compiling, I got the aforementioned message.

Indeed, "Status" is not defined in "cairoimpl.nim". It is defined in "cairo.nim". Should "cairoimpl.nim" import "cairo" or, at least, "Status" from "cairo"?

**Comment by lscrd** [comment]
I tried to import only "Status", but now "Context00" is missing. After that, I need to import "Context", "Surface00", "Surface", etc. And finally compilation fails with a type mismatch. Maybe I misunderstood something.

**Comment by lscrd** [comment]
I found my error. "cairoimpl.nim" is included in "cairo.impl". It should not be imported. Sorry for this false alert.

**Comment by StefanSalewski** [comment]
Yes, it should be clear from the examples that we only import cairo. I will close this.
