### ISSUE TITLE
Missing KeyEvent in SomeEvent

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#9]
I’m not yet sure it has any importance, but it seems that "EventKey" is missing in "SomeEvent".

**Comment by StefanSalewski** [comment]
That may be very true.

The use of "SomeEvent" is a very special hack which was necessary to get it working. I was not really happy about it, so I did not cared for details. Another solution would have been to use Converters, but I tried to avoid that, as it can increase compile time and has some other disadvantages, Araq does not like converters too much also. I am not sure how much additional code is generated by the use of "SomeEvents", I guess it is not little. Maybe later we should rewrite all that Event stuff manually.

I will add the KeyEvent to SomeEvents.

**Comment by lscrd** [comment]
Thanks. I actually need it to use "getKeyval" in the handler for "key-pressed".

**Comment by StefanSalewski** [comment]
Have added KeyEvent and some more. Will close for now.
